import type { QuizQuestion } from '@/content/types';

const questions: QuizQuestion[] = [
  {
    id: 'qq-enablement-01',
    category: 'enablement',
    conceptId: 'sales-playbooks',
    question: 'What is the recommended first step when building a sales playbook for a vertical you have never sold into before?',
    options: [
      'Create a slide template with ICP definitions and talk tracks',
      'Conduct customer and win/loss interviews before writing anything',
      'Copy the existing playbook from a similar vertical and adapt it',
      'Start with the objection library since that is the most used section',
    ],
    correctIndex: 1,
    explanation: 'A playbook should start with research, not a blank template. Conducting customer interviews and win/loss interviews first ensures the content is grounded in real buyer behaviour rather than internal assumptions.',
    hint: 'Think about what distinguishes a credible playbook from shelfware from day one.',
    difficulty: 'easy',
    de: {
      question: 'Was ist der empfohlene erste Schritt beim Aufbau eines Sales Playbooks für ein Vertical, in das man noch nie verkauft hat?',
      options: [
        'Eine Folienvorlage mit ICP-Definitionen und Gesprächsleitfäden erstellen',
        'Kunden- und Win/Loss-Interviews führen, bevor irgendetwas geschrieben wird',
        'Das bestehende Playbook eines ähnlichen Verticals kopieren und anpassen',
        'Mit der Einwand-Bibliothek beginnen, da diese am häufigsten genutzt wird',
      ],
      explanation: 'Ein Playbook sollte mit Recherche beginnen, nicht mit einer leeren Vorlage. Kunden- und Win/Loss-Interviews zuerst zu führen stellt sicher, dass der Inhalt auf echtem Käuferverhalten basiert und nicht auf internen Annahmen.',
      hint: 'Überlege, was ein glaubwürdiges Playbook von Anfang an von bloßer Ablage unterscheidet.',
    },
  },
  {
    id: 'qq-enablement-02',
    category: 'enablement',
    conceptId: 'sales-playbooks',
    question: 'Which metric best indicates that AEs are actually using a sales playbook in their deals?',
    options: [
      'Percentage of AEs who completed a playbook certification within 30 days of launch',
      'Number of times the playbook document was downloaded from the shared drive',
      'Talk tracks and discovery questions appearing in Gong call reviews',
      'AE satisfaction score from the post-launch survey',
    ],
    correctIndex: 2,
    explanation: 'A certification score shows initial learning, but actual usage is only visible when playbook content — talk tracks and discovery questions — shows up in real customer calls recorded in Gong. That is the only proof the playbook is influencing deal execution.',
    hint: 'Consider what evidence directly connects playbook content to deal conversations.',
    difficulty: 'medium',
    de: {
      question: 'Welche Kennzahl zeigt am besten, dass AEs ein Sales Playbook tatsächlich in ihren Deals einsetzen?',
      options: [
        'Prozentsatz der AEs, die innerhalb von 30 Tagen nach Launch eine Playbook-Zertifizierung abgeschlossen haben',
        'Anzahl der Downloads des Playbook-Dokuments aus dem gemeinsamen Laufwerk',
        'Gesprächsleitfäden und Discovery-Fragen, die in Gong-Call-Reviews auftauchen',
        'AE-Zufriedenheitswert aus der Umfrage nach dem Launch',
      ],
      explanation: 'Ein Zertifizierungswert zeigt anfängliches Lernen, aber die tatsächliche Nutzung ist nur sichtbar, wenn Playbook-Inhalte — Gesprächsleitfäden und Discovery-Fragen — in echten, in Gong aufgezeichneten Kundengesprächen auftauchen. Das ist der einzige Beweis, dass das Playbook die Deal-Ausführung beeinflusst.',
      hint: 'Überlege, welcher Beweis Playbook-Inhalte direkt mit Deal-Gesprächen verbindet.',
    },
  },
  {
    id: 'qq-enablement-03',
    category: 'enablement',
    conceptId: 'ae-onboarding',
    question: 'What is the typical ramp quota structure for a new enterprise AE in the first four months?',
    options: [
      '0% / 0% / 50% / 100%',
      '25% / 25% / 50% / 75%',
      '50% / 75% / 100% / 100%',
      '100% / 100% / 100% / 100%',
    ],
    correctIndex: 1,
    explanation: 'A standard ramp for enterprise AEs is 25% of full quota in months 1–2, 50% in month 3, 75% in month 4, and 100% from month 5. This reflects the time required to learn the product, market, and tools before executing independently.',
    difficulty: 'easy',
    de: {
      question: 'Wie sieht die typische Ramp-Quote-Struktur für einen neuen Enterprise-AE in den ersten vier Monaten aus?',
      options: [
        '0 % / 0 % / 50 % / 100 %',
        '25 % / 25 % / 50 % / 75 %',
        '50 % / 75 % / 100 % / 100 %',
        '100 % / 100 % / 100 % / 100 %',
      ],
      explanation: 'Eine Standardhochlaufphase für Enterprise-AEs beträgt 25 % der vollen Quote in Monat 1–2, 50 % in Monat 3, 75 % in Monat 4 und 100 % ab Monat 5. Dies spiegelt die Zeit wider, die benötigt wird, um Produkt, Markt und Tools zu erlernen, bevor man eigenständig arbeitet.',
    },
  },
  {
    id: 'qq-enablement-04',
    category: 'enablement',
    conceptId: 'ae-onboarding',
    question: 'Why does ramp quota design matter for a revenue capacity model, not just for HR?',
    options: [
      'Because ramp quotas determine the base salary bands for new hires',
      'Because the ramp profile determines when new AEs contribute revenue, directly affecting Q2–Q3 projections when hiring in Q1',
      'Because quota design affects how many AEs can share a territory without overlap',
      'Because ramp periods define the legal probationary terms under German labour law',
    ],
    correctIndex: 1,
    explanation: 'Ramp quota is a capacity planning input. A Q1 hire on a six-month ramp does not contribute materially until Q3. A capacity model that assumes full productivity at month two will produce a forecast gap that only becomes visible later in the year.',
    hint: 'Think about the lag between hiring and when a new AE actually generates closed revenue.',
    difficulty: 'medium',
    de: {
      question: 'Warum ist das Design der Ramp-Quote für ein Revenue-Kapazitätsmodell relevant — nicht nur für HR?',
      options: [
        'Weil Ramp-Quoten die Grundgehaltsbänder für neue Mitarbeitende festlegen',
        'Weil das Ramp-Profil bestimmt, wann neue AEs Umsatz beitragen, und so direkt die Q2–Q3-Prognosen beim Q1-Einstellungstermin beeinflusst',
        'Weil das Quota-Design bestimmt, wie viele AEs ein Gebiet ohne Überschneidungen teilen können',
        'Weil Ramp-Perioden die rechtlichen Probezeiten nach deutschem Arbeitsrecht definieren',
      ],
      explanation: 'Die Ramp-Quote ist ein Kapazitätsplanungs-Input. Ein Q1-Einstellungstermin mit einer sechsmonatigen Hochlaufphase trägt erst im Q3 wesentlich bei. Ein Kapazitätsmodell, das volle Produktivität ab Monat zwei annimmt, wird eine Forecast-Lücke erzeugen, die erst später im Jahr sichtbar wird.',
      hint: 'Denke an die Verzögerung zwischen der Einstellung und dem Zeitpunkt, an dem ein neuer AE tatsächlich abgeschlossenen Umsatz erzeugt.',
    },
  },
  {
    id: 'qq-enablement-05',
    category: 'enablement',
    conceptId: 'bant',
    question: 'What is the main limitation of BANT as a qualification framework for complex enterprise deals?',
    options: [
      'BANT requires too many stakeholder interviews and slows down the sales cycle',
      'BANT does not include a step for identifying the legal and procurement process',
      'BANT treats need and authority as pre-existing rather than things a good AE constructs',
      'BANT is only applicable to SaaS deals and does not apply to AI platform sales',
    ],
    correctIndex: 2,
    explanation: 'BANT is buyer-passive: it assumes Budget, Authority, Need, and Timeline already exist and the AE just needs to discover them. In complex enterprise deals, an AE often has to create urgency, build the business case, and navigate distributed authority — none of which BANT accounts for.',
    hint: 'Consider what BANT assumes about the buyer versus what an AE actually has to do in a multi-stakeholder deal.',
    difficulty: 'medium',
    de: {
      question: 'Was ist die Hauptschwäche von BANT als Qualifikationsframework für komplexe Enterprise-Deals?',
      options: [
        'BANT erfordert zu viele Stakeholder-Interviews und verlangsamt den Vertriebszyklus',
        'BANT enthält keinen Schritt zur Identifikation des Rechts- und Beschaffungsprozesses',
        'BANT behandelt Bedarf und Entscheidungsbefugnis als bereits vorhanden, anstatt als etwas, das ein guter AE erst aufbaut',
        'BANT ist nur auf SaaS-Deals anwendbar und gilt nicht für den Verkauf von KI-Plattformen',
      ],
      explanation: 'BANT ist käuferseitig passiv: Es setzt voraus, dass Budget, Entscheidungsbefugnis, Bedarf und Zeitplan bereits existieren und der AE sie nur noch entdecken muss. Bei komplexen Enterprise-Deals muss ein AE oft Dringlichkeit erzeugen, den Business Case aufbauen und verteilte Entscheidungsbefugnis navigieren — all das berücksichtigt BANT nicht.',
      hint: 'Überlege, was BANT über den Käufer voraussetzt, im Vergleich dazu, was ein AE bei einem Multi-Stakeholder-Deal tatsächlich tun muss.',
    },
  },
  {
    id: 'qq-enablement-06',
    category: 'enablement',
    conceptId: 'bant',
    question: 'For which type of deal is BANT actually the most appropriate qualification framework?',
    options: [
      'An enterprise AI platform deal with a 12-month procurement cycle at a German bank',
      'A multi-stakeholder deal where budget does not yet exist and needs to be created',
      'A transactional deal under €50K ACV with a single buyer and a cycle under 30 days',
      'Any deal where Anthropic competes against Azure OpenAI',
    ],
    correctIndex: 2,
    explanation: 'BANT works well for short-cycle, single-buyer, sub-€50K transactional deals where budget, authority, need, and timeline can reasonably be expected to exist up front. It is insufficient for complex enterprise deals that require deeper qualification via MEDDIC or MEDDPICC.',
    difficulty: 'easy',
    de: {
      question: 'Für welche Art von Deal ist BANT tatsächlich das am besten geeignete Qualifikationsframework?',
      options: [
        'Ein Enterprise-KI-Plattform-Deal mit einem 12-monatigen Beschaffungszyklus bei einer deutschen Bank',
        'Ein Multi-Stakeholder-Deal, bei dem noch kein Budget existiert und erst geschaffen werden muss',
        'Ein transaktionaler Deal unter 50.000 € ACV mit einem einzelnen Käufer und einem Zyklus unter 30 Tagen',
        'Jeder Deal, bei dem Anthropic gegen Azure OpenAI konkurriert',
      ],
      explanation: 'BANT funktioniert gut bei kurzfristigen, transaktionalen Deals mit einem einzelnen Käufer und einem ACV unter 50.000 €, bei denen Budget, Entscheidungsbefugnis, Bedarf und Zeitplan vernünftigerweise von Anfang an erwartet werden können. Für komplexe Enterprise-Deals, die eine tiefere Qualifikation über MEDDIC oder MEDDPICC erfordern, ist es unzureichend.',
    },
  },
  {
    id: 'qq-enablement-07',
    category: 'enablement',
    conceptId: 'meddic',
    question: 'In MEDDIC, what distinguishes the Champion from the Economic Buyer?',
    options: [
      'The Champion holds the budget and signs the contract; the Economic Buyer creates internal advocacy',
      'The Champion is an internal advocate with influence who wants you to win; the Economic Buyer is the person with budget authority',
      'The Champion is always the technical evaluator; the Economic Buyer is always the CFO',
      'The Champion and Economic Buyer are interchangeable terms for the same stakeholder',
    ],
    correctIndex: 1,
    explanation: 'In MEDDIC, the Economic Buyer owns the budget and can approve the purchase unilaterally. The Champion is an internal advocate — typically someone who will benefit from the solution — who has credibility and influence but may not control the budget. A deal without a Champion means you are the only one selling internally, which almost always loses.',
    hint: 'One controls money; the other controls internal advocacy.',
    difficulty: 'medium',
    de: {
      question: 'Was unterscheidet in MEDDIC den Champion vom Economic Buyer?',
      options: [
        'Der Champion hält das Budget und unterzeichnet den Vertrag; der Economic Buyer schafft interne Unterstützung',
        'Der Champion ist ein interner Fürsprecher mit Einfluss, der deinen Erfolg will; der Economic Buyer ist die Person mit Budgetentscheidungsbefugnis',
        'Der Champion ist immer der technische Evaluator; der Economic Buyer ist immer der CFO',
        'Champion und Economic Buyer sind austauschbare Begriffe für denselben Stakeholder',
      ],
      explanation: 'Im MEDDIC-Framework besitzt der Economic Buyer das Budget und kann den Kauf eigenständig genehmigen. Der Champion ist ein interner Fürsprecher — typischerweise jemand, der von der Lösung profitieren wird — der Glaubwürdigkeit und Einfluss hat, aber möglicherweise nicht das Budget kontrolliert. Ein Deal ohne Champion bedeutet, dass man der Einzige ist, der intern verkauft — das verliert man fast immer.',
      hint: 'Einer kontrolliert Geld; der andere kontrolliert die interne Unterstützung.',
    },
  },
  {
    id: 'qq-enablement-08',
    category: 'enablement',
    conceptId: 'meddpicc',
    question: 'What are the two components that MEDDPICC adds to MEDDIC?',
    options: [
      'Procurement timeline and Legal escalation path',
      'Pilot scope and Commercial terms',
      'Paper Process and Competition',
      'Pipeline stage and Contract value',
    ],
    correctIndex: 2,
    explanation: 'MEDDPICC extends MEDDIC by adding Paper Process (the legal, procurement, security, and contract steps required to close) and Competition (who else is being evaluated and how you compare). These two additions address the two most common reasons a professionally-won deal still fails to close.',
    difficulty: 'easy',
    de: {
      question: 'Welche zwei Komponenten fügt MEDDPICC gegenüber MEDDIC hinzu?',
      options: [
        'Beschaffungszeitplan und rechtlicher Eskalationspfad',
        'Pilotumfang und kommerzielle Konditionen',
        'Paper Process und Competition',
        'Pipeline-Stage und Vertragswert',
      ],
      explanation: 'MEDDPICC erweitert MEDDIC um den Paper Process (die rechtlichen, Beschaffungs-, Sicherheits- und Vertragsschritte, die zum Abschluss erforderlich sind) und Competition (wer sonst noch evaluiert wird und wie man sich unterscheidet). Diese beiden Ergänzungen adressieren die zwei häufigsten Gründe, warum ein professionell gewonnener Deal trotzdem nicht zum Abschluss kommt.',
    },
  },
  {
    id: 'qq-enablement-09',
    category: 'enablement',
    conceptId: 'meddpicc',
    question: 'Why is the Paper Process component of MEDDPICC especially important for enterprise deals in DACH, and when should an AE start surfacing it?',
    options: [
      'Because DACH companies require English-language contracts, which need early legal translation; surface it at stage 4',
      'Because German and Swiss procurement processes are often more formal and risk-averse than US ones, adding months to cycles; surface it at stage 2 discovery',
      'Because DACH deals always involve a public tender process; surface it only after the POC is complete',
      'Because the Paper Process is a standard step in all deals globally; surface it at the same time as all other qualification criteria',
    ],
    correctIndex: 1,
    explanation: 'In DACH enterprise, security reviews, Data Processing Agreements, DPIA requirements, and multi-level procurement approvals can add three to five months after a verbal agreement. The best AEs surface Paper Process requirements at stage 2 discovery — asking the prospect how they have procured enterprise software in the last twelve months — not at stage five when it is too late to parallel-process.',
    hint: 'Think about what makes DACH procurement specifically slower than a US deal, and the cost of finding out late.',
    difficulty: 'hard',
    de: {
      question: 'Warum ist die Paper-Process-Komponente von MEDDPICC bei Enterprise-Deals im DACH-Raum besonders wichtig, und wann sollte ein AE damit beginnen, sie anzusprechen?',
      options: [
        'Weil DACH-Unternehmen englischsprachige Verträge benötigen, die frühzeitige juristische Übersetzung erfordern; ab Stage 4 ansprechen',
        'Weil deutsche und Schweizer Beschaffungsprozesse oft formaler und risikoaverser als US-amerikanische sind und dem Zyklus Monate hinzufügen können; ab der Stage-2-Discovery ansprechen',
        'Weil DACH-Deals immer einen öffentlichen Ausschreibungsprozess beinhalten; erst nach Abschluss des POCs ansprechen',
        'Weil der Paper Process ein globaler Standardschritt bei allen Deals ist; zum gleichen Zeitpunkt wie alle anderen Qualifikationskriterien ansprechen',
      ],
      explanation: 'Im DACH-Enterprise-Bereich können Sicherheitsreviews, Datenverarbeitungsverträge, DSFA-Anforderungen und mehrstufige Beschaffungsgenehmigungen nach einer mündlichen Vereinbarung drei bis fünf Monate hinzufügen. Die besten AEs sprechen den Paper Process bereits in der Stage-2-Discovery an — indem sie den Interessenten fragen, wie er in den letzten zwölf Monaten Enterprise-Software beschafft hat — nicht erst in Stage 5, wenn eine Parallelbearbeitung nicht mehr möglich ist.',
      hint: 'Überlege, was den DACH-Beschaffungsprozess speziell langsamer als einen US-Deal macht, und welche Kosten eine späte Erkenntnis verursacht.',
    },
  },
  {
    id: 'qq-enablement-10',
    category: 'enablement',
    conceptId: 'competitive-enablement',
    question: 'When a prospect raises a price objection because Azure OpenAI appears cheaper, what is the recommended first step according to competitive enablement best practice?',
    options: [
      'Immediately offer a discount to match Azure OpenAI\'s price point',
      'Escalate to leadership to approve a special pricing exception for the account',
      'Understand why the prospect is engaging with the price argument — price is often a proxy for a perceived value gap',
      'Send a feature comparison table showing Claude\'s superior capabilities',
    ],
    correctIndex: 2,
    explanation: 'A price objection is rarely only about price. It typically signals that the value proposition is not landing clearly enough. The recommended first step is to diagnose the root cause: who raised the price issue, and why does the prospect believe the solutions are comparable enough that price becomes the deciding factor. Only then can you respond effectively — either by building a TCO case, reframing evaluation criteria, or activating executive sponsorship.',
    hint: 'Think about what a price objection usually signals about the perceived value of the solution.',
    difficulty: 'hard',
    de: {
      question: 'Wenn ein Interessent einen Preiseinwand erhebt, weil Azure OpenAI günstiger erscheint, was ist der empfohlene erste Schritt gemäß Best Practice im Competitive Enablement?',
      options: [
        'Sofort einen Rabatt anbieten, um den Preis von Azure OpenAI zu erreichen',
        'An die Führung eskalieren, um eine Sonderpreisausnahme für den Account zu genehmigen',
        'Verstehen, warum der Interessent auf das Preisargument eingeht — Preis ist oft ein Proxy für eine wahrgenommene Wertlücke',
        'Eine Feature-Vergleichstabelle mit den überlegenen Fähigkeiten von Claude schicken',
      ],
      explanation: 'Ein Preiseinwand dreht sich selten nur um den Preis. Er signalisiert typischerweise, dass das Wertversprechen nicht klar genug ankommt. Der empfohlene erste Schritt ist die Diagnose der Ursache: Wer hat das Preisthema angesprochen, und warum glaubt der Interessent, dass die Lösungen vergleichbar genug sind, damit der Preis zum ausschlaggebenden Faktor wird? Erst dann kann man effektiv reagieren — entweder durch den Aufbau eines TCO-Falls, die Neuausrichtung der Evaluierungskriterien oder die Aktivierung von Executive Sponsorship.',
      hint: 'Überlege, was ein Preiseinwand typischerweise über den wahrgenommenen Wert der Lösung signalisiert.',
    },
  },
];

export default questions;
