import type { QuizQuestion } from '@/content/types';

const questions: QuizQuestion[] = [
  {
    id: 'qq-enterprise-sales-01',
    category: 'enterprise-sales',
    conceptId: 'deal-stages',
    question: 'What is the primary purpose of stage gate criteria in an enterprise deal stage model?',
    options: [
      'To reward AEs for the effort they have invested in a deal',
      'To ensure specific factual conditions are met before a deal can advance',
      'To give sales managers a reason to hold pipeline review meetings',
      'To create a paper trail for compliance reporting',
    ],
    correctIndex: 1,
    explanation: 'Stage gates are entry criteria — things that must be objectively true — not effort certificates. A deal advances because specific conditions have been met (e.g., Economic Buyer identified, POC success criteria agreed), not because the AE worked hard on it.',
    difficulty: 'easy',
    de: {
      question: 'Was ist der Hauptzweck von Stage-Gate-Kriterien in einem Enterprise-Deal-Stage-Modell?',
      options: [
        'Um AEs fuer den Aufwand zu belohnen, den sie in einen Deal investiert haben',
        'Um sicherzustellen, dass spezifische sachliche Bedingungen erfuellt sind, bevor ein Deal voranschreiten kann',
        'Um Sales Managern einen Grund fuer Pipeline-Review-Meetings zu geben',
        'Um eine Dokumentationsspur fuer Compliance-Berichte zu erstellen',
      ],
      explanation: 'Stage Gates sind Eintrittskriterien – Dinge, die objektiv wahr sein muessen – keine Leistungsnachweise. Ein Deal schreitet voran, weil spezifische Bedingungen erfuellt sind (z. B. Economic Buyer identifiziert, POC-Erfolgskriterien vereinbart), nicht weil der AE hart daran gearbeitet hat.',
    },
  },
  {
    id: 'qq-enterprise-sales-02',
    category: 'enterprise-sales',
    conceptId: 'deal-stages',
    question: 'In a healthy enterprise pipeline, what is the approximate ideal distribution of deals across early, mid, and late stages?',
    options: [
      '10% early (stages 1–3), 20% mid (stage 4), 70% late (stages 5–6)',
      '25% early (stages 1–3), 50% mid (stage 4), 25% late (stages 5–6)',
      '40% early (stages 1–3), 35% mid (stage 4), 25% late (stages 5–6)',
      '60% early (stages 1–3), 20% mid (stage 4), 20% late (stages 5–6)',
    ],
    correctIndex: 2,
    explanation: 'A healthy pipeline has roughly 40% early-stage (1–3), 35% mid-stage (stage 4), and 25% late-stage (5–6). A pipeline too heavy in late stages means the early funnel is empty and next quarter is at risk — even if the current quarter looks strong.',
    hint: 'Think about what a pipeline heavy at the bottom means for future quarters.',
    difficulty: 'medium',
    de: {
      question: 'Was ist in einer gesunden Enterprise-Pipeline die ideale Verteilung von Deals auf fruehe, mittlere und spaete Stages?',
      options: [
        '10 % Early Stage (1–3), 20 % Mid-Stage (4), 70 % Late Stage (5–6)',
        '25 % Early Stage (1–3), 50 % Mid-Stage (4), 25 % Late Stage (5–6)',
        '40 % Early Stage (1–3), 35 % Mid-Stage (4), 25 % Late Stage (5–6)',
        '60 % Early Stage (1–3), 20 % Mid-Stage (4), 20 % Late Stage (5–6)',
      ],
      explanation: 'Eine gesunde Pipeline hat ungefaehr 40 % Early Stage (1–3), 35 % Mid-Stage (Stage 4) und 25 % Late Stage (5–6). Eine Pipeline, die zu stark im unteren Bereich konzentriert ist, bedeutet, dass der fruehe Funnel leer ist und das naechste Quartal gefaehrdet ist – selbst wenn das aktuelle Quartal stark aussieht.',
      hint: 'Denken Sie daran, was eine Pipeline mit Schwerpunkt am unteren Ende fuer zukuenftige Quartale bedeutet.',
    },
  },
  {
    id: 'qq-enterprise-sales-03',
    category: 'enterprise-sales',
    conceptId: 'multi-threading',
    question: 'What is the defining risk of a single-threaded enterprise deal?',
    options: [
      'The deal will always close more slowly because there is only one approver',
      'If the primary contact leaves, loses influence, or goes on leave, the deal stalls or dies',
      'The AE cannot submit the deal for forecasting without a second contact',
      'Procurement will reject the deal without a co-signer from the buying organisation',
    ],
    correctIndex: 1,
    explanation: 'Single-threaded deals are high-risk because everything depends on one person. If that contact changes role, leaves the company, or loses internal support, you have to restart from zero. Multi-threading ensures the deal has resilience across the buying committee.',
    difficulty: 'easy',
    de: {
      question: 'Was ist das zentrale Risiko eines single-threaded Enterprise-Deals?',
      options: [
        'Der Deal wird immer langsamer abgeschlossen, weil es nur einen Genehmiger gibt',
        'Wenn der primaere Kontakt das Unternehmen verlaesst, an Einfluss verliert oder in Urlaub geht, stockt der Deal oder stirbt ab',
        'Der AE kann den Deal ohne einen zweiten Kontakt nicht zur Prognose einreichen',
        'Das Beschaffungsteam wird den Deal ohne eine zweite Unterschrift aus der kaufenden Organisation ablehnen',
      ],
      explanation: 'Single-threaded Deals sind risikobehaftet, weil alles von einer Person abhaengt. Wenn dieser Kontakt die Rolle wechselt, das Unternehmen verlaesst oder interne Unterstuetzung verliert, muss man von Null anfangen. Multi-Threading stellt sicher, dass der Deal ueber das gesamte Buying Committee hinweg robust ist.',
    },
  },
  {
    id: 'qq-enterprise-sales-04',
    category: 'enterprise-sales',
    conceptId: 'multi-threading',
    question: 'A complete stakeholder map for an enterprise deal should cover how many people across how many organisational dimensions?',
    options: [
      '2–3 people, 1 dimension (technical)',
      '3–5 people, 2 dimensions (business and technical)',
      '5–8 people across at least 3 dimensions (business, technical, and commercial)',
      '10+ people across all departments to ensure no blockers are missed',
    ],
    correctIndex: 2,
    explanation: 'A complete stakeholder map covers 5–8 people across at least three dimensions: business (CDO, line-of-business owner), technical (CTO, CISO, IT), and commercial (CFO, procurement, legal). Each stakeholder entry should include their success criterion, support level, and reporting line.',
    hint: 'Consider who owns budget, who owns technology, and who owns the contract.',
    difficulty: 'medium',
    de: {
      question: 'Eine vollstaendige Stakeholder-Map fuer einen Enterprise-Deal sollte wie viele Personen ueber wie viele organisatorische Dimensionen abdecken?',
      options: [
        '2–3 Personen, 1 Dimension (Technik)',
        '3–5 Personen, 2 Dimensionen (Business und Technik)',
        '5–8 Personen ueber mindestens 3 Dimensionen (Business, Technik und Kommerziell)',
        '10+ Personen aus allen Abteilungen, um sicherzustellen, dass keine Blocker uebersehen werden',
      ],
      explanation: 'Eine vollstaendige Stakeholder-Map umfasst 5–8 Personen ueber mindestens drei Dimensionen: Business (CDO, Line-of-Business-Owner), Technik (CTO, CISO, IT) und Kommerziell (CFO, Beschaffung, Rechtsabteilung). Fuer jeden Stakeholder sollten Erfolgskriterium, Unterstuetzungsniveau und Berichtslinie festgehalten werden.',
      hint: 'Bedenken Sie, wer das Budget besitzt, wer die Technologie verantwortet und wer den Vertrag zeichnet.',
    },
  },
  {
    id: 'qq-enterprise-sales-05',
    category: 'enterprise-sales',
    conceptId: 'executive-sponsorship',
    question: 'What is the primary role of an executive sponsor in an enterprise deal?',
    options: [
      'To negotiate pricing directly with the customer\'s procurement team',
      'To establish peer-level trust with the customer\'s C-suite and signal the seller\'s long-term commitment',
      'To replace the AE as the main point of contact once a deal reaches legal review',
      'To present the full product demo to executive stakeholders who missed earlier sessions',
    ],
    correctIndex: 1,
    explanation: 'The executive sponsor\'s role is not to pitch but to establish peer-level trust and convey strategic commitment. They access C-suite relationships that AEs cannot reach. In DACH financial services, C-level-to-C-level contact signals seriousness and changes how procurement teams engage.',
    difficulty: 'easy',
    de: {
      question: 'Was ist die primaere Rolle eines Executive Sponsors in einem Enterprise-Deal?',
      options: [
        'Preise direkt mit dem Beschaffungsteam des Kunden zu verhandeln',
        'Vertrauen auf Peer-Ebene mit dem C-Suite des Kunden aufzubauen und das langfristige Engagement des Verkaeufers zu signalisieren',
        'Den AE als Hauptansprechpartner zu ersetzen, sobald ein Deal die Rechtsabteilung erreicht',
        'Die vollstaendige Produktdemo fuer Executive Stakeholder zu praesentieren, die frueheren Sitzungen verpasst haben',
      ],
      explanation: 'Die Rolle des Executive Sponsors ist nicht zu pitchen, sondern Vertrauen auf Peer-Ebene aufzubauen und strategisches Engagement zu vermitteln. Er erschliesst C-Suite-Beziehungen, die AEs nicht erreichen koennen. Im DACH-Finanzdienstleistungsbereich signalisiert C-Level-zu-C-Level-Kontakt Ernsthaftigkeit und veraendert die Art und Weise, wie Beschaffungsteams agieren.',
    },
  },
  {
    id: 'qq-enterprise-sales-06',
    category: 'enterprise-sales',
    conceptId: 'executive-sponsorship',
    question: 'Which criterion should trigger the activation of executive sponsorship in a systematic sponsorship programme?',
    options: [
      'Any deal where the AE has had more than 5 meetings with the prospect',
      'Deals above a defined ACV threshold, strategic accounts, or deals stalled at executive level for more than 4 weeks',
      'Every deal in stage 4 or above to signal consistent commitment',
      'Only when the customer explicitly requests to speak with Anthropic leadership',
    ],
    correctIndex: 1,
    explanation: 'A systematic executive sponsorship programme defines clear criteria: deals above a minimum ACV (e.g., €300K), named strategic accounts, or deals stalled at executive level for more than four weeks. Relying solely on customer requests makes sponsorship reactive rather than proactive.',
    hint: 'A good programme is proactive for strategic accounts, not only a firefighting tool for stalled deals.',
    difficulty: 'medium',
    de: {
      question: 'Welches Kriterium sollte die Aktivierung von Executive Sponsorship in einem systematischen Sponsorship-Programm ausloesen?',
      options: [
        'Jeder Deal, bei dem der AE mehr als 5 Meetings mit dem Interessenten hatte',
        'Deals ueber einem definierten ACV-Schwellenwert, strategische Accounts oder Deals, die seit mehr als 4 Wochen auf Executive-Ebene stocken',
        'Jeder Deal in Stage 4 oder hoeher, um konsistentes Engagement zu signalisieren',
        'Nur wenn der Kunde explizit darum bittet, mit der Anthropic-Fuehrung zu sprechen',
      ],
      explanation: 'Ein systematisches Executive-Sponsorship-Programm definiert klare Kriterien: Deals ueber einem Mindest-ACV (z. B. 300.000 EUR), benannte strategische Accounts oder Deals, die seit mehr als vier Wochen auf Executive-Ebene stocken. Sich allein auf Kundenanfragen zu verlassen, macht Sponsorship reaktiv statt proaktiv.',
      hint: 'Ein gutes Programm ist proaktiv fuer strategische Accounts und nicht nur ein Feuerwehr-Tool fuer stockende Deals.',
    },
  },
  {
    id: 'qq-enterprise-sales-07',
    category: 'enterprise-sales',
    conceptId: 'poc-pov',
    question: 'What is the key differentiator between a Proof of Concept (POC) and a Proof of Value (POV)?',
    options: [
      'A POC is run by the customer\'s engineers; a POV is run by the vendor\'s solutions engineers',
      'A POC validates technical feasibility; a POV ties the evaluation to specific, agreed business metrics',
      'A POC is always free; a POV requires the customer to pay a consulting fee',
      'A POC lasts 2 weeks; a POV lasts 6 weeks by definition',
    ],
    correctIndex: 1,
    explanation: 'A POC is a technical validation — does the product work with our data? A POV goes further by linking the evaluation to measurable business outcomes agreed upfront (e.g., reduce document processing time by 40%). POVs are more powerful because they create a concrete commitment and a clear yes/no success criterion.',
    difficulty: 'easy',
    de: {
      question: 'Was ist der wesentliche Unterschied zwischen einem Proof of Concept (POC) und einem Proof of Value (POV)?',
      options: [
        'Ein POC wird von den Ingenieuren des Kunden durchgefuehrt; ein POV wird von den Solutions Engineers des Anbieters durchgefuehrt',
        'Ein POC validiert die technische Machbarkeit; ein POV knuepft die Evaluierung an spezifische, vereinbarte Geschaeftskennzahlen',
        'Ein POC ist immer kostenlos; ein POV erfordert vom Kunden die Zahlung einer Beratungsgebuehr',
        'Ein POC dauert per Definition 2 Wochen; ein POV dauert 6 Wochen',
      ],
      explanation: 'Ein POC ist eine technische Validierung – funktioniert das Produkt mit unseren Daten? Ein POV geht weiter, indem er die Evaluierung an messbare Geschaeftsergebnisse knuepft, die vorab vereinbart wurden (z. B. Dokumentenverarbeitungszeit um 40 % reduzieren). POVs sind wirkungsvoller, weil sie ein konkretes Commitment und ein klares Ja/Nein-Erfolgskriterium schaffen.',
    },
  },
  {
    id: 'qq-enterprise-sales-08',
    category: 'enterprise-sales',
    conceptId: 'poc-pov',
    question: 'A prospect requests a 6-month open-ended evaluation with no defined success criteria. What is the most appropriate response?',
    options: [
      'Accept the request to demonstrate flexibility and avoid risking the relationship',
      'Decline outright and remove the prospect from the pipeline',
      'Reframe the request as a bounded 4-week POC on one use case and ask what must be true for them to proceed commercially',
      'Request that the prospect pays full contract price upfront before any evaluation begins',
    ],
    correctIndex: 2,
    explanation: 'A 6-month open-ended evaluation without success criteria is free consulting. The right response is to reframe it: propose a bounded 4-week POC on a specific use case and ask the qualification question — "What would need to be true at the end of this evaluation for you to move to a commercial agreement?" If they cannot answer, they are not yet ready to buy.',
    hint: 'Ask yourself: if there are no success criteria, how would either party know the evaluation succeeded?',
    difficulty: 'medium',
    de: {
      question: 'Ein Interessent beantragt eine 6-monatige offene Evaluierung ohne definierte Erfolgskriterien. Was ist die angemessenste Reaktion?',
      options: [
        'Die Anfrage akzeptieren, um Flexibilitaet zu demonstrieren und das Risiko zu vermeiden, die Beziehung zu gefaehrden',
        'Direkt ablehnen und den Interessenten aus der Pipeline entfernen',
        'Die Anfrage als begrenzten 4-Wochen-POC zu einem Use Case umrahmen und fragen, was wahr sein muss, damit sie kommerziell weitermachen',
        'Verlangen, dass der Interessent den vollen Vertragspreis im Voraus zahlt, bevor eine Evaluierung beginnt',
      ],
      explanation: 'Eine 6-monatige offene Evaluierung ohne Erfolgskriterien ist kostenloses Consulting. Die richtige Reaktion ist, sie neu zu rahmen: einen begrenzten 4-Wochen-POC zu einem spezifischen Use Case vorschlagen und die Qualifikationsfrage stellen – "Was muesste am Ende dieser Evaluierung wahr sein, damit Sie zu einer kommerziellen Vereinbarung uebergehen?" Wenn sie das nicht beantworten koennen, sind sie noch nicht kaufbereit.',
      hint: 'Fragen Sie sich: Wenn es keine Erfolgskriterien gibt, woher wuerde eine der beiden Parteien wissen, dass die Evaluierung erfolgreich war?',
    },
  },
  {
    id: 'qq-enterprise-sales-09',
    category: 'enterprise-sales',
    conceptId: 'procurement-legal',
    question: 'In DACH enterprise deals, at which deal stage should the Paper Process (procurement and legal path) first be mapped?',
    options: [
      'Stage 5 (Proposal), once commercial terms have been shared',
      'Stage 6 (Legal), when contracting formally begins',
      'Stage 2 (Discovery), as early as possible in the process',
      'Only after the customer has issued a signed letter of intent',
    ],
    correctIndex: 2,
    explanation: 'The Paper Process — the P in MEDDPICC — should be mapped at stage 2, not stage 5. In DACH enterprise deals, procurement and legal review can add 2–6 months after commercial agreement. Discovering this late means you have a verbal yes and a close date that is six months away, which destroys forecast accuracy.',
    hint: 'Think about the P in MEDDPICC and when you need that information to set accurate close dates.',
    difficulty: 'medium',
    de: {
      question: 'In DACH-Enterprise-Deals, in welcher Deal-Stage sollte der Paper Process (Beschaffungs- und Rechtsweg) erstmals kartiert werden?',
      options: [
        'Stage 5 (Proposal), sobald kommerzielle Konditionen kommuniziert wurden',
        'Stage 6 (Legal), wenn die Vertragsverhandlung formal beginnt',
        'Stage 2 (Discovery), so frueh wie moeglich im Prozess',
        'Erst nachdem der Kunde ein unterzeichnetes Letter of Intent ausgestellt hat',
      ],
      explanation: 'Der Paper Process – das P in MEDDPICC – sollte in Stage 2 kartiert werden, nicht in Stage 5. Bei DACH-Enterprise-Deals koennen Beschaffung und Rechtspruefung nach kommerzieller Einigung 2–6 Monate hinzufuegen. Dieses spaet zu entdecken bedeutet, man hat ein muendliches Ja und ein Abschlussdatum, das sechs Monate entfernt ist, was die Forecast-Genauigkeit zerstoert.',
      hint: 'Denken Sie an das P in MEDDPICC und wann Sie diese Information benoetigen, um genaue Abschlussdaten festzulegen.',
    },
  },
  {
    id: 'qq-enterprise-sales-10',
    category: 'enterprise-sales',
    conceptId: 'procurement-legal',
    question: 'Which regulatory and compliance layers are specific to selling AI software to a German bank that would NOT typically apply to a US tech company sale?',
    options: [
      'GDPR data processing agreements and standard MSA redlines',
      'BaFin and MaRisk compliance review, EU AI Act requirements, and 200-question security questionnaires',
      'Annual penetration testing certificates and ISO 27001 certification',
      'Software licence audits and source code escrow requirements',
    ],
    correctIndex: 1,
    explanation: 'German banks face BaFin and MaRisk regulatory requirements for AI systems, EU AI Act obligations for high-risk use cases (e.g., credit scoring, fraud detection), and typically send 200-question security questionnaires. These layers are largely absent in US tech sales contexts and can add 2–6 months to a deal cycle if not anticipated.',
    hint: 'Consider what is unique to German financial regulation and the EU AI regulatory landscape.',
    difficulty: 'hard',
    de: {
      question: 'Welche regulatorischen und Compliance-Schichten sind spezifisch fuer den Verkauf von KI-Software an eine deutsche Bank und wuerden typischerweise NICHT bei einem US-Tech-Unternehmensverkauf anfallen?',
      options: [
        'DSGVO-Datenverarbeitungsvertraege und Standard-MSA-Redlines',
        'BaFin- und MaRisk-Compliance-Review, EU-AI-Act-Anforderungen und 200-Fragen-Sicherheitsfragebögen',
        'Jaehrliche Penetrationstest-Zertifikate und ISO-27001-Zertifizierung',
        'Software-Lizenz-Audits und Anforderungen fuer Source-Code-Hinterlegung',
      ],
      explanation: 'Deutsche Banken unterliegen regulatorischen BaFin- und MaRisk-Anforderungen fuer KI-Systeme, EU-AI-Act-Pflichten fuer Hochrisiko-Use-Cases (z. B. Kredit-Scoring, Betrugserkennung) und senden typischerweise 200-Fragen-Sicherheitsfragebögen. Diese Schichten fehlen in US-amerikanischen Verkaufskontexten weitgehend und koennen einem Deal-Zyklus 2–6 Monate hinzufuegen, wenn sie nicht antizipiert werden.',
      hint: 'Bedenken Sie, was fuer die deutsche Finanzregulierung und die EU-KI-Regulierungslandschaft einzigartig ist.',
    },
  },
  {
    id: 'qq-enterprise-sales-11',
    category: 'enterprise-sales',
    conceptId: 'expansion-motions',
    question: 'What is the most reliable signal that an existing enterprise customer is ready for an expansion conversation?',
    options: [
      'The customer\'s procurement team renews the contract without negotiation',
      'Month-over-month API usage growth of more than 50%, indicating new internal use cases',
      'The customer sends a positive NPS survey response',
      'The customer\'s original champion gets promoted to a more senior role',
    ],
    correctIndex: 1,
    explanation: 'API usage growth above 50% month-over-month is a strong expansion signal because it shows the customer is actively deploying Claude to additional use cases internally — often before they have formally discussed it with the vendor. This usage data is a proactive trigger, not a reactive one.',
    hint: 'Think about what a rapid increase in consumption tells you about the customer\'s internal adoption momentum.',
    difficulty: 'medium',
    de: {
      question: 'Was ist das zuverlaessigste Signal dafuer, dass ein bestehender Enterprise-Kunde bereit fuer ein Expansionsgespraech ist?',
      options: [
        'Das Beschaffungsteam des Kunden erneuert den Vertrag ohne Verhandlung',
        'Monatliches API-Nutzungswachstum von mehr als 50 %, was auf neue interne Use Cases hindeutet',
        'Der Kunde sendet eine positive NPS-Umfrageantwort',
        'Der urspruengliche Champion des Kunden wird in eine hohere Position befördert',
      ],
      explanation: 'API-Nutzungswachstum von ueber 50 % monatlich ist ein starkes Expansionssignal, weil es zeigt, dass der Kunde Claude intern aktiv in weitere Use Cases einfuehrt – oft bevor er das formal mit dem Anbieter besprochen hat. Diese Nutzungsdaten sind ein proaktiver Ausloser, kein reaktiver.',
      hint: 'Denken Sie daran, was eine rasche Steigerung des Verbrauchs Ihnen ueber den internen Adoptionsschwung des Kunden sagt.',
    },
  },
  {
    id: 'qq-enterprise-sales-12',
    category: 'enterprise-sales',
    conceptId: 'expansion-motions',
    question: 'Why should expansion ACV quota be tracked separately from new logo quota?',
    options: [
      'Because expansion deals are reported in a different Salesforce object than new deals',
      'To incentivise both expansion and new logo motions independently, preventing AEs from neglecting one in favour of the other',
      'Because expansion revenue is classified differently for accounting and cannot be mixed with new ARR',
      'So that Customer Success Managers receive commission credit for any expansion they influence',
    ],
    correctIndex: 1,
    explanation: 'If AEs have only a single blended quota, they will naturally focus on whichever motion is easier or faster — often neglecting expansion. Separate expansion quotas create a direct incentive for AEs to run both motions deliberately. This structural decision also enables cleaner measurement of each motion\'s health.',
    hint: 'Consider how compensation structure shapes behaviour: what gets measured and incentivised gets done.',
    difficulty: 'hard',
    de: {
      question: 'Warum sollte die Expansions-ACV-Quote separat von der Neulogo-Quote verfolgt werden?',
      options: [
        'Weil Expansion-Deals in einem anderen Salesforce-Objekt als neue Deals erfasst werden',
        'Um sowohl Expansions- als auch Neulogo-Motions unabhaengig zu incentivieren und zu verhindern, dass AEs eine zugunsten der anderen vernachlaessigen',
        'Weil Expansionsumsaetze buchhalterisch anders klassifiziert werden und nicht mit neuem ARR vermischt werden koennen',
        'Damit Customer Success Manager Provisionsgutschriften fuer jede Expansion erhalten, die sie beeinflussen',
      ],
      explanation: 'Wenn AEs nur eine einzige gemischte Quote haben, werden sie sich natuerlich auf die einfachere oder schnellere Motion konzentrieren – oft die Expansion vernachlaessigen. Separate Expansionsquoten schaffen einen direkten Anreiz fuer AEs, beide Motions gezielt zu betreiben. Diese Strukturentscheidung ermoeglicht auch eine klarere Messung der Gesundheit jeder Motion.',
      hint: 'Bedenken Sie, wie die Verguetungsstruktur das Verhalten praegt: Was gemessen und incentiviert wird, wird auch getan.',
    },
  },
];

export default questions;
