import type { QuizQuestion } from '@/content/types';

const questions: QuizQuestion[] = [
  {
    id: 'qq-gtm-01',
    category: 'gtm',
    conceptId: 'gtm-motion-types',
    question: 'Which of the following best describes a Product-Led Growth (PLG) motion?',
    options: [
      'A direct sales team owns the full cycle from prospecting to close',
      'The product itself drives adoption and conversion without a sales team initiating deals',
      'Sales reps layer enterprise outreach on top of a fixed marketing funnel',
      'Growth is driven primarily by partner referrals and channel resellers',
    ],
    correctIndex: 1,
    explanation: 'PLG means the product is the primary acquisition and expansion mechanism. Users discover value independently, and conversion happens through product experience rather than sales-initiated outreach. Slack is a classic example: free team adoption came first, and sales came later only for larger deals.',
    difficulty: 'easy',
    de: {
      question: 'Welche der folgenden Beschreibungen trifft am besten auf eine Product-Led Growth (PLG)-Motion zu?',
      options: [
        'Ein direktes Vertriebsteam verantwortet den gesamten Zyklus von der Akquise bis zum Abschluss',
        'Das Produkt selbst treibt Adoption und Conversion, ohne dass der Vertrieb Deals initiiert',
        'Sales-Reps schalten Enterprise-Outreach auf einen festen Marketing-Funnel auf',
        'Wachstum wird primär durch Partner-Empfehlungen und Channel-Reseller getrieben',
      ],
      explanation: 'PLG bedeutet, dass das Produkt der primäre Akquise- und Expansionsmechanismus ist. Nutzer entdecken den Mehrwert eigenständig, und die Conversion erfolgt durch die Produkterfahrung, nicht durch vom Vertrieb initiierte Kontaktaufnahme. Slack ist ein klassisches Beispiel: die kostenlose Team-Adoption kam zuerst, und der Vertrieb folgte erst später bei größeren Deals.',
    },
  },
  {
    id: 'qq-gtm-02',
    category: 'gtm',
    conceptId: 'gtm-motion-types',
    question: 'Anthropic has API customers whose usage is growing rapidly. At what point should an AE typically step in to convert this into a formal enterprise deal?',
    options: [
      'Immediately when any API spend is detected, regardless of amount',
      'Only after the customer proactively requests an enterprise contract',
      'When consistent spend growth, multiple teams using the API, or a business-critical use case emerges',
      'After the API credit card expires and a new payment method is needed',
    ],
    correctIndex: 2,
    explanation: 'Jumping in too early can destroy developer goodwill and interrupt an organic adoption cycle. The right triggers are: consistent spend growth, several internal teams adopting the API, or a mission-critical use case appearing. These signals indicate the account is ready for an enterprise conversation about scale, security, and formal procurement.',
    hint: 'Think about what signals show the account is moving from exploration to business-critical dependency.',
    difficulty: 'medium',
    de: {
      question: 'Anthropic hat API-Kunden mit schnell wachsender Nutzung. Ab wann sollte ein AE typischerweise eingreifen, um daraus einen formellen Enterprise-Deal zu machen?',
      options: [
        'Sofort, wenn irgendeine API-Ausgabe erkannt wird, unabhängig von der Höhe',
        'Erst nachdem der Kunde proaktiv einen Enterprise-Vertrag anfragt',
        'Wenn konstantes Ausgabenwachstum, mehrere Teams, die die API nutzen, oder ein geschäftskritischer Anwendungsfall entsteht',
        'Nachdem die API-Kreditkarte abläuft und eine neue Zahlungsmethode benötigt wird',
      ],
      explanation: 'Zu frühes Eingreifen kann das Vertrauen der Entwickler zerstören und einen organischen Adoptionszyklus unterbrechen. Die richtigen Auslöser sind: konstantes Ausgabenwachstum, mehrere interne Teams, die die API nutzen, oder ein geschäftskritischer Anwendungsfall. Diese Signale zeigen, dass der Account bereit für ein Enterprise-Gespräch über Skalierung, Sicherheit und formelle Beschaffung ist.',
      hint: 'Überlege, welche Signale zeigen, dass der Account von der Erkundungsphase zu einer geschäftskritischen Abhängigkeit übergeht.',
    },
  },
  {
    id: 'qq-gtm-03',
    category: 'gtm',
    conceptId: 'icp',
    question: 'What is an Ideal Customer Profile (ICP) primarily used to describe?',
    options: [
      'The individual decision-maker most likely to champion your product internally',
      'The company — defined by firmographic and behavioral attributes — most likely to become a high-value, long-term customer',
      'A scoring model for ranking individual sales opportunities by close probability',
      'A competitive analysis framework comparing your product to alternatives',
    ],
    correctIndex: 1,
    explanation: 'An ICP describes the company, not an individual. It is built from firmographic attributes (size, industry, geography, tech stack) combined with behavioral signals (budget cycle, current pain, initiative sponsorship). This company-level filter focuses selling effort and reduces cycle length by screening out poor-fit accounts early. Persona targeting happens after the ICP filter.',
    difficulty: 'easy',
    de: {
      question: 'Wofür wird ein Ideal Customer Profile (ICP) primär verwendet?',
      options: [
        'Den einzelnen Entscheidungsträger zu beschreiben, der dein Produkt intern am ehesten vorantreiben wird',
        'Das Unternehmen zu beschreiben — definiert durch firmografische und Verhaltensmerkmale — das am wahrscheinlichsten ein hochwertiger, langfristiger Kunde wird',
        'Ein Scoring-Modell zum Einordnen einzelner Verkaufschancen nach Abschlusswahrscheinlichkeit',
        'Ein Wettbewerbsanalyse-Framework zum Vergleich deines Produkts mit Alternativen',
      ],
      explanation: 'Ein ICP beschreibt das Unternehmen, nicht eine Einzelperson. Er wird aus firmografischen Merkmalen (Größe, Branche, Geografie, Tech-Stack) in Kombination mit Verhaltenssignalen (Budgetzyklus, aktueller Schmerzpunkt, Initiative-Sponsoring) aufgebaut. Dieser Filter auf Unternehmensebene fokussiert den Vertriebsaufwand und verkürzt Zyklen, indem schlecht passende Accounts früh herausgefiltert werden. Das Targeting auf Persona-Ebene erfolgt nach dem ICP-Filter.',
    },
  },
  {
    id: 'qq-gtm-04',
    category: 'gtm',
    conceptId: 'icp',
    question: 'An AE team\'s deals keep dying at security review or legal, late in the cycle. What ICP problem does this most likely indicate?',
    options: [
      'The ICP employee-count threshold is set too low, attracting SMBs into the enterprise pipeline',
      'The ICP passes firmographic fit but misses procurement readiness signals like cloud maturity and existing DPA processes',
      'The AEs are targeting the wrong persona and need to reach CFOs instead of CTOs',
      'The product pricing is too high for the segment and needs repositioning',
    ],
    correctIndex: 1,
    explanation: 'Late-stage deal death at security or legal review typically means accounts looked right on paper (firmographics), but lacked procurement readiness. Companies without established cloud data governance, existing DPA processes, or prior enterprise SaaS procurement experience will stall indefinitely once legal gets involved. The fix is to add readiness signals to the ICP definition so these accounts are filtered before AE time is spent.',
    hint: 'Consider the difference between a company that looks like a good fit vs. one that is actually ready to buy.',
    difficulty: 'medium',
    de: {
      question: 'Die Deals eines AE-Teams scheitern immer wieder spät im Zyklus beim Security-Review oder beim Rechtsteam. Welches ICP-Problem deutet das am wahrscheinlichsten an?',
      options: [
        'Der Mitarbeiterzahl-Schwellenwert des ICP ist zu niedrig gesetzt und zieht KMUs in die Enterprise-Pipeline',
        'Der ICP erfüllt firmografische Kriterien, verfehlt aber Signale zur Beschaffungsreife wie Cloud-Reife und bestehende DPA-Prozesse',
        'Die AEs sprechen die falsche Persona an und müssten CFOs statt CTOs erreichen',
        'Die Produktpreisgestaltung ist für das Segment zu hoch und muss neu positioniert werden',
      ],
      explanation: 'Wenn Deals in späten Phasen beim Security- oder Legal-Review scheitern, bedeutet das meist, dass Accounts auf dem Papier richtig aussahen (Firmografie), aber keine Beschaffungsreife hatten. Unternehmen ohne etablierte Cloud-Data-Governance, bestehende DPA-Prozesse oder frühere Enterprise-SaaS-Erfahrung werden auf unbestimmte Zeit blockiert, sobald die Rechtsabteilung involviert ist. Die Lösung ist, Bereitschaftssignale in die ICP-Definition aufzunehmen, damit diese Accounts herausgefiltert werden, bevor AE-Zeit investiert wird.',
      hint: 'Überlege den Unterschied zwischen einem Unternehmen, das gut aussieht, und einem, das tatsächlich bereit ist zu kaufen.',
    },
  },
  {
    id: 'qq-gtm-05',
    category: 'gtm',
    conceptId: 'market-segmentation',
    question: 'What is the primary purpose of market segmentation in a GTM strategy?',
    options: [
      'To reduce headcount by consolidating all customer sizes under a single AE motion',
      'To divide the total addressable market into groups that can be treated differently — each with its own motion, quota model, and success metrics',
      'To identify the single largest revenue opportunity and focus all resources on it',
      'To create marketing personas for content and demand generation campaigns',
    ],
    correctIndex: 1,
    explanation: 'Segmentation is about recognizing that different customer groups require fundamentally different approaches. Enterprise deals have longer cycles, higher ACV, and complex qualification; commercial deals are higher-volume and lighter-touch. Running them through a single motion produces mediocre results for both. Good segmentation enables distinct motions, appropriate AE profiles, and relevant success metrics per group.',
    difficulty: 'easy',
    de: {
      question: 'Was ist der primäre Zweck der Marktsegmentierung in einer GTM-Strategie?',
      options: [
        'Headcount zu reduzieren, indem alle Kundengrößen unter einer einzigen AE-Motion zusammengeführt werden',
        'Den Total Addressable Market in Gruppen aufzuteilen, die unterschiedlich behandelt werden können — jeweils mit eigener Motion, eigenem Quotenmodell und eigenen Erfolgsmetriken',
        'Die größte einzelne Umsatzchance zu identifizieren und alle Ressourcen darauf zu konzentrieren',
        'Marketing-Personas für Content- und Demand-Generation-Kampagnen zu erstellen',
      ],
      explanation: 'Segmentierung bedeutet zu erkennen, dass verschiedene Kundengruppen grundlegend unterschiedliche Ansätze erfordern. Enterprise-Deals haben längere Zyklen, höheren ACV und komplexe Qualifikation; Commercial-Deals sind volumenreicher und schlanker. Beide durch eine einzige Motion zu führen, erzeugt für beide mittelmäßige Ergebnisse. Gute Segmentierung ermöglicht eigenständige Motions, geeignete AE-Profile und relevante Erfolgsmetriken pro Gruppe.',
    },
  },
  {
    id: 'qq-gtm-06',
    category: 'gtm',
    conceptId: 'market-segmentation',
    question: 'In DACH market segmentation for Anthropic, which of the following is a distinct segment that requires different messaging from large German multinationals?',
    options: [
      'The public sector (Bundesbehorden)',
      'The Mittelstand (mid-market industrial companies)',
      'DACH-based subsidiaries of US tech companies',
      'The retail banking sector',
    ],
    correctIndex: 1,
    explanation: 'The Mittelstand — Germany\'s mid-market industrial companies — is explicitly called out as a distinct DACH segment. These companies have different characteristics, buying behaviors, and messaging needs compared to large multinationals (DAX corporations). They often have slower AI adoption timelines and different procurement processes, making a one-size-fits-all enterprise motion inappropriate.',
    hint: 'This is a DACH-specific nuance mentioned directly in the segmentation concept.',
    difficulty: 'medium',
    de: {
      question: 'Welches der folgenden Segmente erfordert im DACH-Markt für Anthropic ein anderes Messaging als große deutsche Konzerne?',
      options: [
        'Der öffentliche Sektor (Bundesbehörden)',
        'Der Mittelstand (mittelständische Industrieunternehmen)',
        'DACH-Niederlassungen von US-Technologieunternehmen',
        'Der Retail-Banking-Sektor',
      ],
      explanation: 'Der Mittelstand — Deutschlands mittelständische Industrieunternehmen — wird explizit als eigenständiges DACH-Segment hervorgehoben. Diese Unternehmen haben andere Eigenschaften, Kaufverhaltensweisen und Messaging-Anforderungen als große Konzerne (DAX-Unternehmen). Sie haben oft langsamere KI-Adoption und andere Beschaffungsprozesse, weshalb eine einheitliche Enterprise-Motion ungeeignet ist.',
      hint: 'Dies ist eine DACH-spezifische Besonderheit, die direkt im Segmentierungskonzept erwähnt wird.',
    },
  },
  {
    id: 'qq-gtm-07',
    category: 'gtm',
    conceptId: 'sales-plays',
    question: 'A sales play is best described as which of the following?',
    options: [
      'A comprehensive document covering every stage of the full sales motion from prospecting to renewal',
      'A repeatable, prescriptive sequence of actions an AE takes to address a specific customer situation — including trigger, persona, talk track, CTA, and success metric',
      'A competitive battle card comparing your product to two or three rival offerings',
      'A pricing matrix that specifies discounting thresholds by deal size and segment',
    ],
    correctIndex: 1,
    explanation: 'A sales play is narrower and more specific than a playbook. It targets one situation (a pain point, use case, or competitive scenario) and prescribes exactly what to do: the trigger that fires the play, the persona to target, the talk track, the supporting content, the call-to-action, and how success is measured. A playbook may contain many plays; a play is not a playbook.',
    difficulty: 'easy',
    de: {
      question: 'Ein Sales Play wird am besten wie folgt beschrieben:',
      options: [
        'Ein umfassendes Dokument, das jede Phase der vollständigen Vertriebsmotion von der Akquise bis zur Verlängerung abdeckt',
        'Eine wiederholbare, vorgeschriebene Abfolge von Maßnahmen, die ein AE unternimmt, um eine spezifische Kundensituation anzugehen — inklusive Auslöser, Persona, Talk Track, CTA und Erfolgsmetrik',
        'Eine Wettbewerbs-Karteikarte, die dein Produkt mit zwei oder drei Mitbewerberangeboten vergleicht',
        'Eine Preismatrix, die Rabattschwellen nach Deal-Größe und Segment festlegt',
      ],
      explanation: 'Ein Sales Play ist enger und spezifischer als ein Playbook. Es zielt auf eine Situation ab (einen Schmerzpunkt, Anwendungsfall oder ein Wettbewerbsszenario) und schreibt genau vor, was zu tun ist: der Auslöser, die Zielpersona, der Talk Track, die unterstützenden Inhalte, der Call-to-Action und die Erfolgsmessung. Ein Playbook kann viele Plays enthalten; ein Play ist kein Playbook.',
    },
  },
  {
    id: 'qq-gtm-08',
    category: 'gtm',
    conceptId: 'sales-plays',
    question: 'You launched a sales play 60 days ago. Activation rate among AEs is high, but no new pipeline has been created. What is the most productive next diagnostic step?',
    options: [
      'Immediately kill the play and start designing a new one from scratch',
      'Increase the number of AEs running the play to generate more volume',
      'Identify exactly where in the sequence conversion is failing — outbound response rate, meeting conversion, or opportunity creation — and talk to AEs about what prospects are saying',
      'Lower the target account threshold and expand the play to smaller companies',
    ],
    correctIndex: 2,
    explanation: 'When AEs are running the play but no pipeline results, the play itself has a flaw — not an adoption problem. The next step is to diagnose at which specific conversion point the play is breaking down. Is outreach being ignored? Are meetings happening but not converting to opps? Talking to AEs reveals what prospects actually say, which exposes whether the message, CTA, trigger, or persona is the root cause. Killing or expanding the play before diagnosing wastes time.',
    hint: 'High activation rules out the adoption problem. Focus on where in the funnel value is leaking.',
    difficulty: 'hard',
    de: {
      question: 'Du hast vor 60 Tagen ein Sales Play gestartet. Die Aktivierungsrate der AEs ist hoch, aber es wurde noch keine neue Pipeline aufgebaut. Was ist der produktivste nächste Diagnoseschritt?',
      options: [
        'Das Play sofort stoppen und von Grund auf ein neues entwerfen',
        'Die Anzahl der AEs erhöhen, die das Play durchführen, um mehr Volumen zu generieren',
        'Genau identifizieren, wo in der Sequenz die Conversion scheitert — Outbound-Antwortrate, Meeting-Conversion oder Opportunity-Erstellung — und mit AEs sprechen, was Interessenten sagen',
        'Den Zielaccount-Schwellenwert senken und das Play auf kleinere Unternehmen ausweiten',
      ],
      explanation: 'Wenn AEs das Play durchführen, aber keine Pipeline entsteht, hat das Play selbst einen Fehler — kein Adoptionsproblem. Der nächste Schritt ist zu diagnostizieren, an welchem spezifischen Conversion-Punkt das Play scheitert. Wird Outreach ignoriert? Finden Meetings statt, aber sie konvertieren nicht zu Opportunities? Gespräche mit AEs zeigen, was Interessenten tatsächlich sagen, was enthüllt, ob Botschaft, CTA, Auslöser oder Persona die Ursache ist. Das Play zu stoppen oder auszuweiten, bevor eine Diagnose gestellt wird, verschwendet Zeit.',
      hint: 'Hohe Aktivierungsrate schließt das Adoptionsproblem aus. Fokussiere darauf, wo im Funnel Wert verloren geht.',
    },
  },
  {
    id: 'qq-gtm-09',
    category: 'gtm',
    conceptId: 'value-propositions',
    question: 'Enterprise GTM requires value propositions at three distinct layers. Which combination correctly names all three?',
    options: [
      'Product layer, pricing layer, and competitive layer',
      'Company level, vertical level, and persona level',
      'Awareness level, consideration level, and decision level',
      'Executive layer, manager layer, and end-user layer',
    ],
    correctIndex: 1,
    explanation: 'A complete enterprise value proposition operates at three levels: company level (why Anthropic vs. any AI vendor — answers the economic buyer\'s strategic question), vertical level (why Claude specifically for financial services — addresses industry-specific pain), and persona level (why Claude for the CISO vs. CDO vs. CFO — each stakeholder has different success criteria). Enterprise deals involve 5-8 stakeholders, so a single-layer message cannot cover all of them.',
    difficulty: 'easy',
    de: {
      question: 'Enterprise-GTM erfordert Value Propositions auf drei verschiedenen Ebenen. Welche Kombination benennt alle drei korrekt?',
      options: [
        'Produktebene, Preisebene und Wettbewerbsebene',
        'Unternehmensebene, vertikale Ebene und Persona-Ebene',
        'Awareness-Ebene, Consideration-Ebene und Decision-Ebene',
        'Executive-Ebene, Manager-Ebene und Endnutzer-Ebene',
      ],
      explanation: 'Eine vollständige Enterprise-Value-Proposition funktioniert auf drei Ebenen: Unternehmensebene (warum Anthropic vs. irgendeinem KI-Anbieter — beantwortet die strategische Frage des Economic Buyers), vertikale Ebene (warum Claude speziell für Financial Services — adressiert branchenspezifischen Schmerzpunkt) und Persona-Ebene (warum Claude für den CISO vs. CDO vs. CFO — jeder Stakeholder hat unterschiedliche Erfolgskriterien). Enterprise-Deals involvieren 5–8 Stakeholder, weshalb eine einstufige Botschaft sie nicht alle erreichen kann.',
    },
  },
  {
    id: 'qq-gtm-10',
    category: 'gtm',
    conceptId: 'value-propositions',
    question: 'When building a value proposition for a German bank\'s CDO evaluating Claude for document processing, which approach is most effective according to enterprise GTM best practices?',
    options: [
      'Lead with Claude\'s benchmark performance scores and model size to establish technical superiority',
      'Compare Claude feature-by-feature against OpenAI GPT-4 to show differentiated capabilities',
      'Lead with the business outcome ("reduce analyst time on regulatory reporting by 60% without compliance risk") and anchor on regulatory compliance, data sovereignty, and ROI',
      'Highlight the breadth of use cases Claude can support across the entire enterprise to show flexibility',
    ],
    correctIndex: 2,
    explanation: 'Enterprise procurement teams — and CDOs specifically — do not buy benchmarks or feature lists. They buy business outcomes and risk reduction. The most effective approach is to lead with a quantified outcome relevant to their role (regulatory reporting efficiency), add the compliance and data sovereignty hooks that are critical in BaFin-regulated environments, and close with an ROI framing showing payback within 12 months. Feature comparisons and breadth arguments are explicitly flagged as things to avoid.',
    hint: 'Think about what a CDO at a regulated bank actually needs to justify the purchase internally.',
    difficulty: 'medium',
    de: {
      question: 'Beim Aufbau einer Value Proposition für den CDO einer deutschen Bank, der Claude für die Dokumentenverarbeitung evaluiert, welcher Ansatz ist laut Enterprise-GTM-Best-Practices am effektivsten?',
      options: [
        'Mit Claudes Benchmark-Performance-Scores und Modellgröße führen, um technische Überlegenheit zu zeigen',
        'Claude Feature für Feature gegen OpenAI GPT-4 vergleichen, um differenzierte Fähigkeiten aufzuzeigen',
        'Mit dem Business Outcome führen ("Analysten-Zeit bei der regulatorischen Berichterstattung um 60% reduzieren — ohne Compliance-Risiko") und auf regulatorische Compliance, Datensouveränität und ROI verankern',
        'Die Breite der Anwendungsfälle hervorheben, die Claude im gesamten Unternehmen unterstützen kann, um Flexibilität zu zeigen',
      ],
      explanation: 'Enterprise-Beschaffungsteams — und CDOs insbesondere — kaufen keine Benchmarks oder Feature-Listen. Sie kaufen Business Outcomes und Risikoreduktion. Der effektivste Ansatz ist, mit einem quantifizierten, rollenrelevanten Ergebnis zu führen (Effizienz bei der regulatorischen Berichterstattung), Compliance- und Datensouveränitäts-Hooks hinzuzufügen, die in BaFin-regulierten Umgebungen entscheidend sind, und mit einem ROI-Framing abzuschließen, das eine Amortisation innerhalb von 12 Monaten zeigt. Feature-Vergleiche und Breiten-Argumente sind explizit als Dinge markiert, die es zu vermeiden gilt.',
      hint: 'Überlege, was ein CDO bei einer regulierten Bank tatsächlich braucht, um den Kauf intern zu rechtfertigen.',
    },
  },
  {
    id: 'qq-gtm-11',
    category: 'gtm',
    conceptId: 'vertical-gtm',
    question: 'According to the Vertical GTM framework, which two verticals in DACH should be the Year-1 priority for Anthropic\'s enterprise motion — and why?',
    options: [
      'Retail and Manufacturing — because they have the largest number of companies in Germany',
      'Healthcare and Public Sector — because they have the highest data sensitivity requirements',
      'Financial Services and Technology — because FS has high ACV with strong Claude differentiation, and Technology has faster cycles with technical buyers',
      'Manufacturing and Retail — because both have large-scale automation needs that Claude can address immediately',
    ],
    correctIndex: 2,
    explanation: 'The framework scores verticals on market size x ICP density x deal velocity x Claude differentiation x regulatory tailwind. Financial Services comes out as Tier 1: high ACV, the strongest differentiation around safety and compliance (BaFin, EU AI Act), and the best fit for Claude\'s documented safety properties. Technology is Tier 1 secondary: faster cycles, technical buyers already familiar with APIs, and reasonable deal sizes. Healthcare is Tier 2 because strict data-residency requirements add 3-6 months. Manufacturing is Tier 2 because AI adoption is still early-stage. Depth in two verticals beats breadth across five.',
    hint: 'Score each vertical on deal size, differentiation, cycle speed, and regulatory alignment.',
    difficulty: 'hard',
    de: {
      question: 'Welche zwei Branchen im DACH-Raum sollten laut dem Vertical-GTM-Framework die Jahr-1-Priorität für Anthropics Enterprise-Motion sein — und warum?',
      options: [
        'Retail und Manufacturing — weil sie die größte Anzahl an Unternehmen in Deutschland haben',
        'Healthcare und öffentlicher Sektor — weil sie die höchsten Datenschutzanforderungen haben',
        'Financial Services und Technology — weil FS hohen ACV mit starker Claude-Differenzierung hat, und Technology schnellere Zyklen mit technischen Käufern',
        'Manufacturing und Retail — weil beide großflächige Automatisierungsbedarfe haben, die Claude sofort adressieren kann',
      ],
      explanation: 'Das Framework bewertet Branchen nach Marktgröße × ICP-Dichte × Deal-Velocity × Claude-Differenzierung × regulatorischem Rückenwind. Financial Services ergibt Tier 1: hoher ACV, stärkste Differenzierung rund um Sicherheit und Compliance (BaFin, EU-KI-Gesetz) und beste Passung zu Claudes dokumentierten Sicherheitseigenschaften. Technology ist Tier 1 sekundär: schnellere Zyklen, technische Käufer, die bereits mit APIs vertraut sind, und angemessene Deal-Größen. Healthcare ist Tier 2, weil strenge Datenresidenzanforderungen 3–6 Monate hinzufügen. Manufacturing ist Tier 2, weil die KI-Adoption noch früh ist. Tiefe in zwei Branchen schlägt Breite in fünf.',
      hint: 'Bewerte jede Branche nach Deal-Größe, Differenzierung, Zyklusgeschwindigkeit und regulatorischer Ausrichtung.',
    },
  },
  {
    id: 'qq-gtm-12',
    category: 'gtm',
    conceptId: 'vertical-gtm',
    question: 'Which combination of signals most reliably indicates that a vertical is ready for a dedicated sales play rather than a generic enterprise pitch?',
    options: [
      'The vertical has more than 500 potential accounts in the TAM and at least one Fortune 500 logo',
      'Two to three closed deals with an understood buying pattern, a repeatable trigger event, a specific named use case, and a reference customer available for the pitch',
      'The vertical has been included in the annual marketing plan and a campaign budget has been allocated',
      'At least one AE has expressed personal interest in specializing in the vertical',
    ],
    correctIndex: 1,
    explanation: 'A dedicated sales play requires evidence, not aspiration. The five readiness signals are: (1) 2-3 closed deals so the buying pattern is understood, (2) a repeatable trigger event (regulation, board mandate, competitive pressure), (3) a use case specific enough to name (\'KYC document review\' rather than \'AI for banking\'), (4) a reference customer to use in the pitch, and (5) win rate in the vertical already above average. Without these, you are still hypothesis-testing and a generic enterprise pitch is more appropriate. A play without a case study is just a pitch deck with a vertical logo.',
    hint: 'Think about what evidence-based signals separate a proven pattern from a hypothesis.',
    difficulty: 'hard',
    de: {
      question: 'Welche Kombination von Signalen zeigt am zuverlässigsten an, dass eine Branche bereit für ein dediziertes Sales Play ist, statt für einen generischen Enterprise-Pitch?',
      options: [
        'Die Branche hat mehr als 500 potenzielle Accounts im TAM und mindestens ein Fortune-500-Logo',
        'Zwei bis drei abgeschlossene Deals mit einem verstandenen Kaufmuster, ein wiederholbares Auslöser-Ereignis, ein spezifisch benannter Anwendungsfall und ein für den Pitch verfügbarer Referenzkunde',
        'Die Branche wurde in den Jahresmarketingplan aufgenommen und ein Kampagnenbudget wurde zugeteilt',
        'Mindestens ein AE hat persönliches Interesse daran geäußert, sich auf die Branche zu spezialisieren',
      ],
      explanation: 'Ein dediziertes Sales Play erfordert Belege, keine Absichten. Die fünf Bereitschaftssignale sind: (1) 2–3 abgeschlossene Deals, sodass das Kaufmuster verstanden wird, (2) ein wiederholbares Auslöser-Ereignis (Regulierung, Vorstandsmandat, Wettbewerbsdruck), (3) ein Anwendungsfall, der spezifisch genug ist, um ihn zu benennen (\'KYC-Dokumentenprüfung\' statt \'KI für Banking\'), (4) ein Referenzkunde für den Pitch und (5) eine Gewinnrate in der Branche bereits über dem Durchschnitt. Ohne diese Signale testet man noch Hypothesen, und ein generischer Enterprise-Pitch ist angemessener. Ein Play ohne Fallstudie ist nur ein Pitch-Deck mit einem Branchen-Logo.',
      hint: 'Überlege, welche evidenzbasierten Signale ein bewährtes Muster von einer Hypothese unterscheiden.',
    },
  },
];

export default questions;
