import type { QuizQuestion } from '@/content/types';

const questions: QuizQuestion[] = [
  {
    id: 'qq-industry-segments-01',
    category: 'industry-segments',
    conceptId: 'dach-banks',
    question: 'Which sub-segment of DACH banking is considered the highest-compliance environment and requires data to remain within national borders?',
    options: [
      'Universal banks such as Deutsche Bank and Commerzbank',
      'Savings banks (Sparkassen) and cooperative banks (Volksbanken)',
      'Swiss private banks such as UBS, Vontobel, and Pictet',
      'Private banks and asset managers such as Berenberg and Julius Bär',
    ],
    correctIndex: 2,
    explanation: 'Swiss banks operate under FINMA regulation, which enforces the strictest data-residency requirements in DACH. Data must remain in Switzerland, meaning Anthropic must have a Swiss endpoint before a deal can proceed. This is the highest compliance bar in the region.',
    hint: 'Think about which country has its own financial regulator that sits outside the EU framework.',
    difficulty: 'easy',
    de: {
      question: 'Welches DACH-Bankensub-Segment gilt als das Umfeld mit den höchsten Compliance-Anforderungen und verlangt, dass Daten innerhalb der Landesgrenzen verbleiben?',
      options: [
        'Universalbanken wie Deutsche Bank und Commerzbank',
        'Sparkassen und Genossenschaftsbanken (Volksbanken)',
        'Schweizer Privatbanken wie UBS, Vontobel und Pictet',
        'Privatbanken und Asset Manager wie Berenberg und Julius Bär',
      ],
      explanation: 'Schweizer Banken unterliegen der FINMA-Regulierung, die die strengsten Datenresidenz-Anforderungen in DACH durchsetzt. Daten müssen in der Schweiz verbleiben, was bedeutet, dass Anthropic einen Schweizer Endpunkt benötigt, bevor ein Deal voranschreiten kann. Das ist die höchste Compliance-Hürde in der Region.',
      hint: 'Denken Sie daran, welches Land eine eigene Finanzaufsichtsbehörde hat, die außerhalb des EU-Rahmens steht.',
    },
  },
  {
    id: 'qq-industry-segments-02',
    category: 'industry-segments',
    conceptId: 'dach-banks',
    question: 'When trying to scale across the Sparkassen-Verbund in Germany, what is the correct approach rather than selling to each savings bank individually?',
    options: [
      'Engage the BaFin regulator to mandate platform adoption across all Sparkassen',
      'Work through the DSGV or the Finanzinformatik IT subsidiary to reach the network',
      'Partner with Deutsche Bank, which acts as a central clearing bank for the Sparkassen',
      'Focus exclusively on the five largest Sparkassen by assets and let the rest follow',
    ],
    correctIndex: 1,
    explanation: 'The Sparkassen-Verbund is highly fragmented — decisions are made at the individual institution or association level, not centrally. To scale, the right approach is to work through the DSGV (the umbrella association) or Finanzinformatik, the dedicated IT subsidiary that provides shared infrastructure to hundreds of savings banks.',
    hint: 'The Sparkassen have a shared IT infrastructure provider — that is the lever for scale.',
    difficulty: 'medium',
    de: {
      question: 'Wenn man versucht, im Sparkassen-Verbund in Deutschland zu skalieren, was ist der richtige Ansatz statt des Verkaufs an jede Sparkasse einzeln?',
      options: [
        'Die BaFin als Regulierer einschalten, um die Plattformadoption für alle Sparkassen anzuordnen',
        'Über den DSGV oder die IT-Tochter Finanzinformatik das Netzwerk erschließen',
        'Mit der Deutschen Bank zusammenarbeiten, die als Zentralbank für die Sparkassen fungiert',
        'Sich ausschließlich auf die fünf größten Sparkassen nach Bilanzsumme konzentrieren und den Rest folgen lassen',
      ],
      explanation: 'Der Sparkassen-Verbund ist stark fragmentiert — Entscheidungen werden auf Einzel-Instituts- oder Verbandsebene getroffen, nicht zentral. Um zu skalieren, ist der richtige Ansatz, über den DSGV (den Dachverband) oder Finanzinformatik zu arbeiten, die dedizierte IT-Tochter, die Hunderten von Sparkassen gemeinsame Infrastruktur bereitstellt.',
      hint: 'Die Sparkassen haben einen gemeinsamen IT-Infrastrukturanbieter — das ist der Hebel für Skalierung.',
    },
  },
  {
    id: 'qq-industry-segments-03',
    category: 'industry-segments',
    conceptId: 'dach-banks',
    question: 'A CISO at a German bank demands model explainability documentation before approving a Claude deployment. Which Claude capability directly addresses this requirement?',
    options: [
      'Claude\'s 200K-token context window, which processes entire loan files in one pass',
      'Constitutional AI and cite-with-sources output mode, which let analysts trace every output back to source material',
      'Claude\'s multilingual capability, enabling outputs in both German and English simultaneously',
      'Anthropic\'s SOC 2 certification, which confirms data is not retained after inference',
    ],
    correctIndex: 1,
    explanation: 'Constitutional AI produces outputs that are principled and documented, while cite-with-sources mode lets analysts trace every claim to its source. Together, these allow compliance teams to take explainability evidence directly to regulators — turning a sales differentiator into genuine procurement collateral.',
    hint: 'The CISO needs to be able to show regulators how a model arrives at its outputs.',
    difficulty: 'medium',
    de: {
      question: 'Ein CISO einer deutschen Bank fordert Modell-Erklärbarkeits-Dokumentation, bevor er eine Claude-Implementierung genehmigt. Welche Claude-Fähigkeit adressiert diese Anforderung direkt?',
      options: [
        'Claudes 200K-Token-Kontextfenster, das vollständige Kreditakten in einem Durchgang verarbeitet',
        'Constitutional AI und der Cite-with-Sources-Ausgabemodus, der Analysten ermöglicht, jeden Output auf Quellmaterial zurückzuverfolgen',
        'Claudes mehrsprachige Fähigkeit, die Ausgaben gleichzeitig auf Deutsch und Englisch ermöglicht',
        'Anthropics SOC-2-Zertifizierung, die bestätigt, dass Daten nach der Inferenz nicht gespeichert werden',
      ],
      explanation: 'Constitutional AI erzeugt Ausgaben, die prinzipienbasiert und dokumentiert sind, während der Cite-with-Sources-Modus Analysten ermöglicht, jede Aussage auf ihre Quelle zurückzuverfolgen. Zusammen ermöglichen diese Compliance-Teams, Erklärbarkeits-Nachweise direkt bei Regulierern vorzulegen — und verwandeln ein Verkaufsargument in echtes Beschaffungsmaterial.',
      hint: 'Der CISO muss in der Lage sein, Regulierern zu zeigen, wie ein Modell zu seinen Ausgaben gelangt.',
    },
  },
  {
    id: 'qq-industry-segments-04',
    category: 'industry-segments',
    conceptId: 'dach-insurance',
    question: 'Why should reinsurers like Munich Re be targeted before primary insurers in a DACH GTM strategy?',
    options: [
      'Reinsurers have simpler regulatory requirements than primary insurers under Solvency II',
      'Reinsurers are structurally more tech-forward and a win there creates a reference that resonates sector-wide',
      'Reinsurers have smaller deal sizes, making them faster to close and good for building a reference base',
      'Primary insurers are already served by competing AI vendors, leaving reinsurers as the only available segment',
    ],
    correctIndex: 1,
    explanation: 'Reinsurers like Munich Re and Swiss Re run analytics at scale, have internal AI teams, and move significantly faster than primary insurers. Critically, they advise primary insurers on risk models and technology — so a successful deployment at Munich Re creates an informal reference that influences purchasing decisions across the entire DACH insurance market.',
    difficulty: 'medium',
    de: {
      question: 'Warum sollten Rückversicherer wie Munich Re im Rahmen einer DACH-GTM-Strategie vor Erstversicherern angesprochen werden?',
      options: [
        'Rückversicherer haben einfachere regulatorische Anforderungen als Erstversicherer unter Solvency II',
        'Rückversicherer sind strukturell technologieaffiner und ein Erfolg dort schafft eine Referenz, die branchenweit Widerhall findet',
        'Rückversicherer haben kleinere Deal-Größen, was sie schneller abschließbar macht und gut für den Aufbau einer Referenzbasis ist',
        'Erstversicherer werden bereits von konkurrierenden KI-Anbietern bedient, sodass Rückversicherer das einzige verfügbare Segment darstellen',
      ],
      explanation: 'Rückversicherer wie Munich Re und Swiss Re betreiben Analysen in großem Maßstab, haben interne KI-Teams und bewegen sich deutlich schneller als Erstversicherer. Entscheidend ist, dass sie Erstversicherer bei Risikomodellen und Technologie beraten — ein erfolgreicher Einsatz bei Munich Re schafft daher eine informelle Referenz, die Kaufentscheidungen im gesamten DACH-Versicherungsmarkt beeinflusst.',
    },
  },
  {
    id: 'qq-industry-segments-05',
    category: 'industry-segments',
    conceptId: 'dach-insurance',
    question: 'In DACH insurance, which three AI use cases are identified as the most commercially promising for Claude?',
    options: [
      'Customer acquisition, pricing optimization, and investment portfolio analysis',
      'Fraud detection, claims automation, and underwriting documentation',
      'Regulatory capital calculation, reinsurance treaty pricing, and actuarial modelling',
      'Customer service chatbots, policy renewal reminders, and agent training',
    ],
    correctIndex: 1,
    explanation: 'The top three use cases in DACH insurance are fraud detection, claims automation, and underwriting documentation. These map directly to Claude\'s core strengths: long context handles multi-document cross-referencing for fraud; multilingual German processing accelerates claims handling; and Constitutional AI provides the auditability that underwriting decisions require under Solvency II.',
    difficulty: 'easy',
    de: {
      question: 'Welche drei KI-Anwendungsfälle werden in der DACH-Versicherungsbranche als die kommerziell vielversprechendsten für Claude identifiziert?',
      options: [
        'Kundengewinnung, Preisoptimierung und Anlageportfolioanalyse',
        'Betrugserkennung, Schadenautomatisierung und Zeichnungsdokumentation',
        'Regulatorische Kapitalberechnung, Rückversicherungsvertragspreisgestaltung und versicherungsmathematische Modellierung',
        'Kundenservice-Chatbots, Policenverlängerungserinnerungen und Agentenschulung',
      ],
      explanation: 'Die drei wichtigsten Anwendungsfälle in der DACH-Versicherungsbranche sind Betrugserkennung, Schadenautomatisierung und Zeichnungsdokumentation. Diese entsprechen direkt Claudes Kernstärken: Long-Context verarbeitet die Querverweisierung mehrerer Dokumente bei der Betrugserkennung; mehrsprachige deutsche Verarbeitung beschleunigt die Schadensbearbeitung; und Constitutional AI liefert die Auditierbarkeit, die Zeichnungsentscheidungen unter Solvency II erfordern.',
    },
  },
  {
    id: 'qq-industry-segments-06',
    category: 'industry-segments',
    conceptId: 'dach-insurance',
    question: 'How does the sales motion for DACH insurance differ from DACH banking in terms of champion profile and value proposition?',
    options: [
      'Both segments are sold to CDOs; insurance focuses on cost reduction while banking focuses on revenue growth',
      'Insurance is sold to COOs and Claims Operations leaders on process efficiency; banking is sold to CDOs on regulatory risk reduction',
      'Insurance requires a procurement-led motion while banking relies on executive sponsorship from the CEO',
      'Both segments share the same champion profile; the difference lies only in the regulatory framework (Solvency II vs. EU AI Act)',
    ],
    correctIndex: 1,
    explanation: 'Banking sells to CDOs on the value of regulatory risk reduction — Constitutional AI and data residency are core messages. Insurance sells to COOs and Claims Operations leaders on operational efficiency — document processing speed, fraud detection accuracy, and claims throughput. The champion, the value message, and the success metric are fundamentally different between the two segments.',
    hint: 'Think about who feels the pain directly: a compliance team worried about regulators, or a operations team processing thousands of documents.',
    difficulty: 'medium',
    de: {
      question: 'Wie unterscheidet sich die Sales Motion für DACH-Versicherungen von DACH-Banken hinsichtlich des Champion-Profils und der Wertproposition?',
      options: [
        'Beide Segmente werden an CDOs verkauft; Versicherungen konzentrieren sich auf Kostensenkung, Banking auf Umsatzwachstum',
        'Versicherungen werden an COOs und Claims-Operations-Leiter auf der Grundlage von Prozesseffizienz verkauft; Banking wird an CDOs auf der Grundlage von regulatorischer Risikoreduktion verkauft',
        'Versicherungen erfordern eine beschaffungsgetriebene Bewegung, während Banking auf Executive-Sponsoring vom CEO angewiesen ist',
        'Beide Segmente teilen dasselbe Champion-Profil; der Unterschied liegt nur im regulatorischen Rahmen (Solvency II vs. EU AI Act)',
      ],
      explanation: 'Banking verkauft an CDOs auf Basis der regulatorischen Risikoreduktion — Constitutional AI und Datenresidenz sind die Kernbotschaften. Versicherungen verkaufen an COOs und Claims-Operations-Leiter auf Basis operativer Effizienz — Dokumentenverarbeitungsgeschwindigkeit, Betrugserkennungsgenauigkeit und Schadens-Durchsatz. Der Champion, die Wertbotschaft und die Erfolgskennzahl sind zwischen den beiden Segmenten grundlegend unterschiedlich.',
      hint: 'Denken Sie daran, wer den Schmerz direkt spürt: ein Compliance-Team, das sich um Regulierer sorgt, oder ein Operations-Team, das Tausende von Dokumenten verarbeitet.',
    },
  },
  {
    id: 'qq-industry-segments-07',
    category: 'industry-segments',
    conceptId: 'dach-telcos',
    question: 'T-Systems is best understood as which type of commercial opportunity for Anthropic?',
    options: [
      'A direct enterprise customer only, because their internal IT complexity creates sufficient standalone deal size',
      'A regulated customer like a bank, requiring full EU AI Act compliance documentation before any engagement',
      'Both a direct customer and a potential channel partner, giving access to 40,000+ enterprise clients at scale',
      'A competitor, since T-Systems already resells AI services from Microsoft and Google to its clients',
    ],
    correctIndex: 2,
    explanation: 'T-Systems is Deutsche Telekom\'s enterprise IT arm with 40,000+ clients. It should be approached both as a direct customer (internal AI use cases in knowledge management and service desk) and as a channel partner (reselling Claude to its enormous enterprise client base). The recommended sequencing is direct deal first in year 1 to establish trust, then partner agreement in year 2.',
    hint: 'T-Systems has over 40,000 enterprise clients — think about what that means for indirect reach.',
    difficulty: 'easy',
    de: {
      question: 'T-Systems ist am besten als welche Art von kommerzieller Möglichkeit für Anthropic zu verstehen?',
      options: [
        'Ausschließlich als Direktkunde, da die interne IT-Komplexität ausreichende eigenständige Deal-Größen schafft',
        'Als regulierter Kunde wie eine Bank, der vollständige EU-AI-Act-Compliance-Dokumentation vor jeglichem Engagement erfordert',
        'Sowohl als Direktkunde als auch als potenzieller Channel-Partner, der Zugang zu über 40.000 Enterprise-Kunden in großem Maßstab bietet',
        'Als Konkurrent, da T-Systems bereits KI-Dienste von Microsoft und Google an seine Kunden weiterverkauft',
      ],
      explanation: 'T-Systems ist der Enterprise-IT-Arm der Deutschen Telekom mit über 40.000 Kunden. Es sollte sowohl als Direktkunde (interne KI-Anwendungsfälle im Wissensmanagement und Service Desk) als auch als Channel-Partner angesprochen werden (Weiterverkauf von Claude an seine riesige Enterprise-Kundenbasis). Die empfohlene Reihenfolge ist direkter Deal zuerst in Jahr 1 zum Aufbau von Vertrauen, dann Partnerschaftsvereinbarung in Jahr 2.',
      hint: 'T-Systems hat über 40.000 Enterprise-Kunden — denken Sie darüber nach, was das für indirekte Reichweite bedeutet.',
    },
  },
  {
    id: 'qq-industry-segments-08',
    category: 'industry-segments',
    conceptId: 'dach-telcos',
    question: 'Compared to DACH banks, what is the typical enterprise deal cycle length for DACH telcos, and what primarily drives this difference?',
    options: [
      'Telcos take longer — 18–24 months — because network infrastructure decisions require board-level approval',
      'Telcos and banks take the same time (12–18 months) because both are regulated industries with formal procurement',
      'Telcos are faster — 3–9 months — driven by revenue pressure from connectivity commoditization and existing developer teams who can move quickly',
      'Telcos are faster — 1–3 months — because they are unregulated and can bypass normal procurement channels',
    ],
    correctIndex: 2,
    explanation: 'DACH telcos close enterprise AI deals in 3–9 months versus 12–18 months for banks. The speed comes from two structural factors: intense revenue pressure from commoditization of connectivity forcing faster AI investment decisions, and large internal developer teams already fluent with API integrations who can accelerate from evaluation to production contract.',
    hint: 'Consider what business pressure telcos face that banks do not, and who inside a telco is likely already experimenting with AI APIs.',
    difficulty: 'medium',
    de: {
      question: 'Wie lang ist die typische Enterprise-Deal-Zykluslänge für DACH-Telcos im Vergleich zu DACH-Banken, und was treibt diesen Unterschied hauptsächlich an?',
      options: [
        'Telcos dauern länger — 18–24 Monate — da Netzwerkinfrastrukturentscheidungen eine Genehmigung auf Vorstandsebene erfordern',
        'Telcos und Banken benötigen die gleiche Zeit (12–18 Monate), da beide regulierte Branchen mit formeller Beschaffung sind',
        'Telcos sind schneller — 3–9 Monate — getrieben durch Umsatzdruck aus der Kommoditisierung der Konnektivität und bestehende Entwicklerteams, die sich schnell bewegen können',
        'Telcos sind schneller — 1–3 Monate — da sie unreguliert sind und normale Beschaffungskanäle umgehen können',
      ],
      explanation: 'DACH-Telcos schließen Enterprise-KI-Deals in 3–9 Monaten ab, gegenüber 12–18 Monaten für Banken. Die Geschwindigkeit ergibt sich aus zwei strukturellen Faktoren: intensiver Umsatzdruck durch die Kommoditisierung der Konnektivität, der schnellere KI-Investitionsentscheidungen erzwingt, und große interne Entwicklerteams, die bereits mit API-Integrationen vertraut sind und von der Evaluation zum Produktionsvertrag beschleunigen können.',
      hint: 'Überlegen Sie, welchem Geschäftsdruck Telcos ausgesetzt sind, den Banken nicht haben, und wer innerhalb eines Telcos wahrscheinlich bereits mit KI-APIs experimentiert.',
    },
  },
  {
    id: 'qq-industry-segments-09',
    category: 'industry-segments',
    conceptId: 'dach-mittelstand',
    question: 'Why does a standard US-style direct enterprise sales motion fail to scale for the German Mittelstand?',
    options: [
      'Mittelstand companies exclusively use open-source software and are philosophically opposed to vendor relationships',
      'The ACV per deal is too low and sales cycles too long relative to the cost of direct coverage, making customer acquisition cost exceed deal value',
      'GDPR restrictions prevent Mittelstand companies from signing data processing agreements with non-EU AI vendors',
      'Mittelstand companies already have exclusive contracts with German IT vendors that prohibit competing solutions',
    ],
    correctIndex: 1,
    explanation: 'The economics of direct enterprise selling break down for Mittelstand: typical ACVs of €20K–€150K combined with 6–12 month sales cycles and significant buyer education requirements mean customer acquisition cost exceeds deal value. The correct GTM model is indirect — building a channel through SAP partners, regional system integrators, and industry associations like the IHK and VDMA.',
    hint: 'Consider the unit economics: what does it cost Anthropic to run a full enterprise sales cycle, and how does that compare to typical deal value in this segment?',
    difficulty: 'hard',
    de: {
      question: 'Warum scheitert eine Standard-US-amerikanische direkte Enterprise-Vertriebsbewegung bei der Skalierung für den deutschen Mittelstand?',
      options: [
        'Mittelstandsunternehmen verwenden ausschließlich Open-Source-Software und sind grundsätzlich gegen Anbieterbeziehungen',
        'Der ACV pro Deal ist zu niedrig und die Verkaufszyklen zu lang im Verhältnis zu den Kosten der direkten Abdeckung, sodass die Kundenakquisitionskosten den Deal-Wert übersteigen',
        'DSGVO-Beschränkungen hindern Mittelstandsunternehmen daran, Datenverarbeitungsverträge mit Nicht-EU-KI-Anbietern zu unterzeichnen',
        'Mittelstandsunternehmen haben bereits Exklusivverträge mit deutschen IT-Anbietern, die konkurrierende Lösungen verbieten',
      ],
      explanation: 'Die Wirtschaftlichkeit des direkten Enterprise-Verkaufs bricht für den Mittelstand zusammen: typische ACVs von 20.000–150.000 € in Kombination mit 6–12-monatigen Verkaufszyklen und erheblichem Bedarf an Käuferaufklärung bedeuten, dass die Kundenakquisitionskosten den Deal-Wert übersteigen. Das richtige GTM-Modell ist indirekt — den Aufbau eines Channels über SAP-Partner, regionale Systemintegratoren und Branchenverbände wie IHK und VDMA.',
      hint: 'Betrachten Sie die Stückkostenrechnung: Was kostet Anthropic ein vollständiger Enterprise-Verkaufszyklus, und wie verhält sich das im Vergleich zum typischen Deal-Wert in diesem Segment?',
    },
  },
  {
    id: 'qq-industry-segments-10',
    category: 'industry-segments',
    conceptId: 'dach-mittelstand',
    question: 'In a Mittelstand GTM strategy, which ecosystem organizations serve as the most credible entry points for peer-to-peer reference selling?',
    options: [
      'LinkedIn Germany, Xing, and the Wirtschaftswoche subscriber network',
      'BaFin, the Bundesbank, and the Federal Ministry of Finance',
      'VDMA, IHK chapters, and Bitkom forums — industry association networks where Mittelstand CEOs meet peers from the same sector',
      'Management consultancies like McKinsey and Roland Berger who serve Mittelstand clients',
    ],
    correctIndex: 2,
    explanation: 'The VDMA (German Engineering Federation), IHK (Chambers of Commerce), and Bitkom (digital industry association) are the primary networks through which Mittelstand CEOs interact with peers from the same industry and region. A reference from a respected peer at an IHK event or VDMA chapter meeting carries far more weight than any case study — Mittelstand CEOs trust other Mittelstand CEOs, not vendor marketing.',
    hint: 'These are the physical and institutional venues where a Mittelstand CEO in precision engineering or specialty chemicals would meet others in their field.',
    difficulty: 'hard',
    de: {
      question: 'Welche Ökosystem-Organisationen dienen in einer Mittelstand-GTM-Strategie als die glaubwürdigsten Einstiegspunkte für das Peer-to-Peer-Referenzverkaufen?',
      options: [
        'LinkedIn Deutschland, Xing und das Wirtschaftswoche-Abonnentennetzwerk',
        'BaFin, Bundesbank und das Bundesministerium der Finanzen',
        'VDMA, IHK-Chapters und Bitkom-Foren — Branchenverbandsnetzwerke, in denen Mittelstands-CEOs Gleichgesinnte aus derselben Branche treffen',
        'Unternehmensberatungen wie McKinsey und Roland Berger, die Mittelstandskunden betreuen',
      ],
      explanation: 'Der VDMA (Verband Deutscher Maschinen- und Anlagenbau), die IHK (Industrie- und Handelskammern) und Bitkom (digitaler Branchenverband) sind die primären Netzwerke, über die Mittelstands-CEOs mit Gleichgesinnten aus derselben Branche und Region interagieren. Eine Referenz von einem angesehenen Kollegen bei einer IHK-Veranstaltung oder einem VDMA-Chapter-Treffen hat weit mehr Gewicht als jede Fallstudie — Mittelstands-CEOs vertrauen anderen Mittelstands-CEOs, nicht Anbieter-Marketing.',
      hint: 'Dies sind die physischen und institutionellen Treffpunkte, an denen ein Mittelstands-CEO aus der Präzisionstechnik oder Spezialchemie andere aus seinem Fachgebiet treffen würde.',
    },
  },
];

export default questions;
