import type { QuizQuestion } from '@/content/types';

const questions: QuizQuestion[] = [
  {
    id: 'qq-metrics-01',
    category: 'metrics',
    conceptId: 'arr-mrr',
    question: 'A deal closes for €500K in year 1, including €50K of one-time implementation fees. What is the correct ARR to book?',
    options: [
      '€500K — the full contract value is booked as ARR',
      '€450K — one-time fees are excluded from ARR',
      '€400K — professional services and implementation are always excluded',
      '€550K — implementation fees are amortized and added to ARR',
    ],
    correctIndex: 1,
    explanation: 'ARR only includes recurring subscription revenue. One-time implementation fees are excluded because they are not recurring. The correct ARR is €500K minus the €50K one-time fee = €450K.',
    difficulty: 'easy',
    de: {
      question: 'Ein Deal schließt mit 500.000 € in Jahr 1 ab, einschließlich 50.000 € einmaliger Implementierungsgebühren. Welchen ARR bucht man korrekt?',
      options: [
        '500.000 € — der gesamte Vertragswert wird als ARR gebucht',
        '450.000 € — einmalige Gebühren werden vom ARR ausgeschlossen',
        '400.000 € — Professional Services und Implementierung werden immer ausgeschlossen',
        '550.000 € — Implementierungsgebühren werden amortisiert und zum ARR addiert',
      ],
      explanation: 'ARR umfasst ausschließlich wiederkehrende Abonnementumsätze. Einmalige Implementierungsgebühren werden ausgeschlossen, da sie nicht wiederkehrend sind. Der korrekte ARR beträgt 500.000 € minus 50.000 € = 450.000 €.',
    },
  },
  {
    id: 'qq-metrics-02',
    category: 'metrics',
    conceptId: 'arr-mrr',
    question: 'What is the correct relationship between ARR and MRR?',
    options: [
      'MRR = ARR × 12',
      'ARR = MRR ÷ 12',
      'ARR = MRR × 12',
      'ARR and MRR are independent metrics with no fixed relationship',
    ],
    correctIndex: 2,
    explanation: 'ARR is the annualized equivalent of MRR. Since MRR is a monthly figure, you multiply by 12 to get the annual figure: ARR = MRR × 12. Equivalently, MRR = ARR ÷ 12.',
    difficulty: 'easy',
    de: {
      question: 'Wie lautet die korrekte Beziehung zwischen ARR und MRR?',
      options: [
        'MRR = ARR × 12',
        'ARR = MRR ÷ 12',
        'ARR = MRR × 12',
        'ARR und MRR sind unabhängige Kennzahlen ohne festes Verhältnis',
      ],
      explanation: 'ARR ist der auf das Jahr hochgerechnete Wert von MRR. Da MRR eine monatliche Kennzahl ist, wird sie mit 12 multipliziert, um den Jahreswert zu erhalten: ARR = MRR × 12. Entsprechend gilt: MRR = ARR ÷ 12.',
    },
  },
  {
    id: 'qq-metrics-03',
    category: 'metrics',
    conceptId: 'nrr-grr',
    question: 'What is the key structural difference between NRR and GRR?',
    options: [
      'GRR includes expansion revenue; NRR does not',
      'NRR includes expansion revenue; GRR does not — and GRR is capped at 100%',
      'NRR measures monthly retention; GRR measures annual retention',
      'GRR is calculated per customer; NRR is calculated per cohort',
    ],
    correctIndex: 1,
    explanation: 'NRR (Net Revenue Retention) includes expansion (upsells, seat additions) minus contraction and churn, so it can exceed 100%. GRR (Gross Revenue Retention) only measures what was retained — it excludes expansion entirely and is therefore capped at 100%.',
    difficulty: 'easy',
    de: {
      question: 'Was ist der entscheidende strukturelle Unterschied zwischen NRR und GRR?',
      options: [
        'GRR beinhaltet Expansionsumsätze; NRR nicht',
        'NRR beinhaltet Expansionsumsätze; GRR nicht — und GRR ist auf 100 % begrenzt',
        'NRR misst monatliche Retention; GRR misst jährliche Retention',
        'GRR wird pro Kunde berechnet; NRR wird pro Kohorte berechnet',
      ],
      explanation: 'NRR (Net Revenue Retention) umfasst Expansion (Upsells, zusätzliche Lizenzen) minus Kontraktion und Churn und kann daher 100 % übersteigen. GRR (Gross Revenue Retention) misst nur, was gehalten wurde — Expansion ist vollständig ausgeschlossen, weshalb GRR auf 100 % begrenzt ist.',
    },
  },
  {
    id: 'qq-metrics-04',
    category: 'metrics',
    conceptId: 'nrr-grr',
    question: 'A SaaS business reports GRR of 88% and NRR of 102%. Which statement best describes the situation?',
    options: [
      'The business is healthy — NRR above 100% means the customer base is compounding',
      'There is a serious retention problem: 12% of customers churn annually, and expansion barely covers the churn hole',
      'The business should invest heavily in new logo acquisition to accelerate growth',
      'GRR of 88% is excellent for enterprise SaaS; NRR of 102% confirms strong unit economics',
    ],
    correctIndex: 1,
    explanation: 'GRR of 88% means 12% of revenue is churning every year before any expansion — that is a retention problem. NRR of 102% means expansion from surviving customers barely covers the churn hole. The business is not compounding; it should fix churn before investing in expansion or new logo acquisition.',
    hint: 'Think about what each metric reveals independently, then combine the picture.',
    difficulty: 'medium',
    de: {
      question: 'Ein SaaS-Unternehmen meldet einen GRR von 88 % und einen NRR von 102 %. Welche Aussage beschreibt die Situation am treffendsten?',
      options: [
        'Das Unternehmen ist gesund — NRR über 100 % bedeutet, dass die Kundenbasis wächst',
        'Es gibt ein ernstes Retention-Problem: 12 % der Kunden churnen jährlich, und Expansion deckt das Churn-Loch kaum',
        'Das Unternehmen sollte stark in Neukundengewinnung investieren, um das Wachstum zu beschleunigen',
        'Ein GRR von 88 % ist exzellent für Enterprise-SaaS; ein NRR von 102 % bestätigt starke Unit Economics',
      ],
      explanation: 'GRR von 88 % bedeutet, dass 12 % des Umsatzes jährlich verloren geht — das ist ein Retention-Problem. NRR von 102 % zeigt, dass Expansion von verbliebenen Kunden das Churn-Loch kaum deckt. Das Unternehmen wächst nicht exponentiell; es sollte zuerst Churn beheben, bevor in Expansion oder Neukundengewinnung investiert wird.',
      hint: 'Überlege, was jede Kennzahl unabhängig aussagt, und kombiniere dann das Gesamtbild.',
    },
  },
  {
    id: 'qq-metrics-05',
    category: 'metrics',
    conceptId: 'cac-ltv',
    question: 'Which LTV:CAC ratio is considered the minimum healthy threshold for a SaaS business?',
    options: [
      '1x — you need to at least break even on acquisition',
      '2x — a 2x return on acquisition cost is sufficient',
      '3x — below this threshold you are likely destroying value',
      '5x — anything below 5x indicates poor unit economics',
    ],
    correctIndex: 2,
    explanation: 'The standard benchmark is LTV:CAC > 3x for a healthy SaaS business, with > 5x being excellent. A ratio of 1.8x or 2x means the business is likely destroying value in that segment — the cost to acquire customers is too high relative to their lifetime contribution.',
    difficulty: 'easy',
    de: {
      question: 'Welches LTV:CAC-Verhältnis gilt als Mindest-Gesundheitsschwelle für ein SaaS-Unternehmen?',
      options: [
        '1x — man muss zumindest die Akquisitionskosten wieder einfahren',
        '2x — eine 2-fache Rendite auf die Akquisitionskosten ist ausreichend',
        '3x — unterhalb dieser Schwelle vernichtet man wahrscheinlich Wert',
        '5x — alles unter 5x deutet auf schlechte Unit Economics hin',
      ],
      explanation: 'Der Standardbenchmark liegt bei LTV:CAC > 3x für ein gesundes SaaS-Unternehmen, mit > 5x als exzellentem Wert. Ein Verhältnis von 1,8x oder 2x bedeutet, dass das Unternehmen in diesem Segment wahrscheinlich Wert vernichtet — die Akquisitionskosten sind im Verhältnis zum Lebenszeitbeitrag zu hoch.',
    },
  },
  {
    id: 'qq-metrics-06',
    category: 'metrics',
    conceptId: 'cac-ltv',
    question: 'What is the correct formula for LTV in a SaaS context?',
    options: [
      'LTV = ACV × number of years retained',
      'LTV = (ACV × gross margin) ÷ churn rate',
      'LTV = total revenue from customer ÷ CAC',
      'LTV = ARR × NRR',
    ],
    correctIndex: 1,
    explanation: 'LTV = (ACV × gross margin) ÷ churn rate. This formula accounts for both the profitability of the revenue (gross margin) and how long the customer stays (the inverse of churn rate). A lower churn rate extends the lifetime, dramatically increasing LTV.',
    hint: 'The formula must incorporate profitability and customer lifetime, not just raw revenue.',
    difficulty: 'medium',
    de: {
      question: 'Wie lautet die korrekte Formel für LTV im SaaS-Kontext?',
      options: [
        'LTV = ACV × Anzahl der gebundenen Jahre',
        'LTV = (ACV × Bruttomarge) ÷ Churn-Rate',
        'LTV = Gesamtumsatz des Kunden ÷ CAC',
        'LTV = ARR × NRR',
      ],
      explanation: 'LTV = (ACV × Bruttomarge) ÷ Churn-Rate. Diese Formel berücksichtigt sowohl die Profitabilität des Umsatzes (Bruttomarge) als auch die Verweildauer des Kunden (Kehrwert der Churn-Rate). Eine niedrigere Churn-Rate verlängert die Lifetime und erhöht den LTV erheblich.',
      hint: 'Die Formel muss Profitabilität und Kundenlaufzeit berücksichtigen, nicht nur den Rohumsatz.',
    },
  },
  {
    id: 'qq-metrics-07',
    category: 'metrics',
    conceptId: 'sales-velocity',
    question: 'What is the correct sales velocity formula?',
    options: [
      '(Win rate × Average deal value) ÷ Sales cycle length',
      '(Number of opportunities × Win rate × Average deal value) ÷ Average sales cycle length',
      'Number of opportunities × Win rate × Average sales cycle length',
      '(Pipeline value × Win rate) ÷ Number of opportunities',
    ],
    correctIndex: 1,
    explanation: 'Sales velocity = (Number of opportunities × Win rate × Average deal value) ÷ Average sales cycle length. The output is revenue generated per day. All four variables must be present: volume (opportunity count), quality (win rate), size (deal value), and speed (cycle length).',
    difficulty: 'easy',
    de: {
      question: 'Wie lautet die korrekte Sales-Velocity-Formel?',
      options: [
        '(Abschlussquote × Durchschnittlicher Deal-Wert) ÷ Verkaufszykluslänge',
        '(Anzahl der Opportunities × Abschlussquote × Durchschnittlicher Deal-Wert) ÷ Durchschnittliche Verkaufszykluslänge',
        'Anzahl der Opportunities × Abschlussquote × Durchschnittliche Verkaufszykluslänge',
        '(Pipeline-Wert × Abschlussquote) ÷ Anzahl der Opportunities',
      ],
      explanation: 'Sales Velocity = (Anzahl der Opportunities × Abschlussquote × Durchschnittlicher Deal-Wert) ÷ Durchschnittliche Verkaufszykluslänge. Das Ergebnis ist der pro Tag generierte Umsatz. Alle vier Variablen müssen vorhanden sein: Volumen (Opportunity-Anzahl), Qualität (Abschlussquote), Größe (Deal-Wert) und Geschwindigkeit (Zykluslänge).',
    },
  },
  {
    id: 'qq-metrics-08',
    category: 'metrics',
    conceptId: 'sales-velocity',
    question: 'A DACH sales team has an average sales cycle of 90 days. If they compress it to 70 days while keeping all other variables constant, by approximately how much does sales velocity improve?',
    options: [
      'Approximately 11% improvement',
      'Approximately 22% improvement',
      'Approximately 29% improvement',
      'Approximately 44% improvement',
    ],
    correctIndex: 2,
    explanation: 'Sales velocity is inversely proportional to cycle length. Moving from 90 to 70 days: 90 ÷ 70 ≈ 1.286, which is approximately a 29% improvement. Compressing the cycle is one of the highest-leverage velocity levers because it affects the denominator directly.',
    hint: 'Since cycle length is the denominator, the improvement is calculated as the ratio of old to new cycle length.',
    difficulty: 'medium',
    de: {
      question: 'Ein DACH-Vertriebsteam hat einen durchschnittlichen Verkaufszyklus von 90 Tagen. Wenn dieser auf 70 Tage komprimiert wird und alle anderen Variablen konstant bleiben, um wie viel verbessert sich die Sales Velocity ungefähr?',
      options: [
        'Ungefähr 11 % Verbesserung',
        'Ungefähr 22 % Verbesserung',
        'Ungefähr 29 % Verbesserung',
        'Ungefähr 44 % Verbesserung',
      ],
      explanation: 'Sales Velocity ist umgekehrt proportional zur Zykluslänge. Wechsel von 90 auf 70 Tage: 90 ÷ 70 ≈ 1,286, also ungefähr 29 % Verbesserung. Die Komprimierung des Zyklus ist einer der wirkungsvollsten Velocity-Hebel, da er direkt den Nenner beeinflusst.',
      hint: 'Da die Zykluslänge der Nenner ist, ergibt sich die Verbesserung aus dem Verhältnis der alten zur neuen Zykluslänge.',
    },
  },
  {
    id: 'qq-metrics-09',
    category: 'metrics',
    conceptId: 'pipeline-coverage',
    question: 'What pipeline coverage ratio is typically required for enterprise sales to have high confidence in hitting the revenue target?',
    options: [
      '1–2x — one dollar of pipeline for every dollar of target is sufficient',
      '2–3x — double coverage accounts for deals that slip',
      '3–4x — enterprise win rates and slippage require this level of buffer',
      '6–8x — large deal variance in enterprise demands very high coverage',
    ],
    correctIndex: 2,
    explanation: 'Enterprise sales typically requires 3–4x pipeline coverage because enterprise win rates are 20–35% and deals frequently slip due to procurement delays, budget freezes, or champion changes. Coverage below 2x is a red flag, while above 5x often indicates pipeline inflation with low-probability deals.',
    difficulty: 'easy',
    de: {
      question: 'Welches Pipeline-Coverage-Verhältnis ist im Enterprise-Vertrieb typischerweise erforderlich, um das Umsatzziel mit hoher Sicherheit zu erreichen?',
      options: [
        '1–2x — ein Euro Pipeline für jeden Euro Ziel ist ausreichend',
        '2–3x — doppelte Coverage berücksichtigt verschiebende Deals',
        '3–4x — Enterprise-Abschlussquoten und Deal-Verschiebungen erfordern diesen Puffer',
        '6–8x — hohe Deal-Varianz im Enterprise-Bereich erfordert sehr hohe Coverage',
      ],
      explanation: 'Enterprise-Vertrieb erfordert typischerweise eine 3–4-fache Pipeline-Coverage, da Enterprise-Abschlussquoten bei 20–35 % liegen und Deals häufig durch Beschaffungsverzögerungen, Budget-Einfrierungen oder Champion-Wechsel verschoben werden. Coverage unter 2x ist ein Warnsignal, während über 5x oft Pipeline-Aufblähung mit Deals geringer Wahrscheinlichkeit anzeigt.',
    },
  },
  {
    id: 'qq-metrics-10',
    category: 'metrics',
    conceptId: 'pipeline-coverage',
    question: 'A team has 4x pipeline coverage but consistently closes only 70% of forecast. What is the most likely root cause?',
    options: [
      'The revenue target is set too high and should be reduced',
      'The team needs more AEs to work the existing pipeline',
      'The pipeline is inflated with unqualified or stale deals that are not truly closeable',
      'The forecast model is miscalculating expected close dates',
    ],
    correctIndex: 2,
    explanation: '4x coverage with 70% attainment is a classic sign of pipeline inflation — deals sitting in the pipeline that are not qualified or have gone stale. The solution is not more headcount or lower targets; it is tightening stage-entry criteria, flagging deals with no activity in 30+ days, and requiring completed qualification (e.g., MEDDPICC) before deals advance in the funnel.',
    hint: 'Coverage and attainment contradict each other here — ask why high coverage does not translate to closing.',
    difficulty: 'medium',
    de: {
      question: 'Ein Team hat eine 4-fache Pipeline-Coverage, schließt aber regelmäßig nur 70 % des Forecasts ab. Was ist die wahrscheinlichste Ursache?',
      options: [
        'Das Umsatzziel ist zu hoch gesetzt und sollte reduziert werden',
        'Das Team braucht mehr AEs, um die vorhandene Pipeline zu bearbeiten',
        'Die Pipeline ist mit unqualifizierten oder veralteten Deals aufgebläht, die nicht wirklich abschlussreif sind',
        'Das Forecast-Modell berechnet die erwarteten Abschlussdaten falsch',
      ],
      explanation: '4-fache Coverage bei 70 % Erreichung ist ein klassisches Zeichen für Pipeline-Aufblähung — Deals in der Pipeline, die nicht qualifiziert sind oder veraltet sind. Die Lösung liegt nicht in mehr Headcount oder niedrigeren Zielen, sondern in der Verschärfung der Stage-Eintrittskriterien, der Markierung inaktiver Deals und der Pflichterfüllung von Qualifikationsanforderungen (z. B. MEDDPICC) vor dem Voranschreiten.',
      hint: 'Coverage und Erreichung widersprechen sich hier — frage, warum hohe Coverage sich nicht in Abschlüssen niederschlägt.',
    },
  },
  {
    id: 'qq-metrics-11',
    category: 'metrics',
    conceptId: 'win-rate',
    question: 'A DACH team has an overall win rate of 18% but a 38% win rate in Financial Services. What is the strategically correct response?',
    options: [
      'Investigate why FS is outperforming and expand into more verticals to bring up the overall rate',
      'Double down on Financial Services (where it works) before spreading to verticals with sub-15% win rates',
      'Reduce the FS focus — a 38% win rate means deals are too easy and the team is leaving money on the table',
      'The 18% overall rate is fine for a new market; no action needed until the second year of operation',
    ],
    correctIndex: 1,
    explanation: 'A 38% win rate in FS tells you the ICP is right, the message lands, and POCs convert in that vertical. An 18% overall rate tells you other verticals are dragging the average down. The strategic move is to double down where the motion works, not to spread thin across verticals with sub-15% win rates where you are likely selling to the wrong buyers.',
    hint: 'Win rate differences across verticals are signals about ICP fit, not just messaging.',
    difficulty: 'medium',
    de: {
      question: 'Ein DACH-Team hat eine Gesamt-Abschlussquote von 18 %, aber 38 % im Financial-Services-Bereich. Was ist die strategisch richtige Reaktion?',
      options: [
        'Untersuchen, warum FS besser abschneidet, und in weitere Verticals expandieren, um die Gesamtquote zu steigern',
        'Im Financial-Services-Bereich verdoppeln (wo es funktioniert), bevor in Verticals mit unter 15 % Abschlussquote expandiert wird',
        'Den FS-Fokus reduzieren — eine 38 % Abschlussquote bedeutet, dass Deals zu einfach sind und das Team Geld auf dem Tisch lässt',
        'Die 18 % Gesamtquote ist für einen neuen Markt in Ordnung; keine Maßnahmen bis zum zweiten Betriebsjahr',
      ],
      explanation: 'Eine Abschlussquote von 38 % im FS-Bereich zeigt, dass der ICP stimmt, die Botschaft ankommt und POCs in diesem Vertical konvertieren. Eine Gesamtquote von 18 % zeigt, dass andere Verticals den Durchschnitt nach unten ziehen. Der strategische Schritt ist, dort zu verdoppeln, wo die Bewegung funktioniert, nicht sich dünn über Verticals mit unter 15 % Abschlussquoten zu verteilen.',
      hint: 'Unterschiede in der Abschlussquote zwischen Verticals sind Signale über ICP-Eignung, nicht nur Messaging.',
    },
  },
  {
    id: 'qq-metrics-12',
    category: 'metrics',
    conceptId: 'conversion-rates',
    question: 'A pipeline review shows only 28% of SQLs convert to qualified Opportunities (SQL→Opp). What is the most likely diagnosis and correct fix?',
    options: [
      'The marketing team is generating too many leads; reduce inbound volume',
      'The SQL stage definition is too loose, or AEs are not completing proper discovery before creating Opportunities — tighten qualification criteria',
      'Win rate is too low; the fix is to add more competitive battle cards',
      'ACV is too low; the fix is to move upmarket and increase minimum deal size',
    ],
    correctIndex: 1,
    explanation: 'A 28% SQL→Opp conversion means 72% of qualified leads never become real pipeline — the bottleneck is at qualification, not conversion or close. The most likely cause is that the SQL definition is too loose (e.g., any meeting becomes an SQL) or AEs skip proper discovery before creating an Opportunity. The fix is to tighten stage-entry criteria and require a qualification checklist (e.g., MEDDIC) before a deal advances to Opportunity stage.',
    hint: 'Stage conversion drop-offs point precisely to where the sales process is breaking down.',
    difficulty: 'hard',
    de: {
      question: 'Ein Pipeline-Review zeigt, dass nur 28 % der SQLs zu qualifizierten Opportunities konvertieren (SQL→Opp). Was ist die wahrscheinlichste Diagnose und die richtige Lösung?',
      options: [
        'Das Marketing-Team generiert zu viele Leads; Inbound-Volumen reduzieren',
        'Die SQL-Stage-Definition ist zu locker, oder AEs führen keine ordentliche Discovery durch, bevor sie Opportunities erstellen — Qualifikationskriterien verschärfen',
        'Die Abschlussquote ist zu niedrig; die Lösung ist das Hinzufügen weiterer Wettbewerbs-Battle-Cards',
        'Der ACV ist zu niedrig; die Lösung ist der Wechsel in obere Marktsegmente und eine höhere Mindest-Deal-Größe',
      ],
      explanation: 'Eine SQL→Opp-Konversion von 28 % bedeutet, dass 72 % der qualifizierten Leads nie echte Pipeline werden — der Engpass liegt bei der Qualifikation, nicht bei Konversion oder Abschluss. Die wahrscheinlichste Ursache ist, dass die SQL-Definition zu locker ist (z. B. wird jedes Meeting ein SQL) oder AEs die ordentliche Discovery überspringen. Die Lösung ist die Verschärfung der Stage-Eintrittskriterien und die Einführung einer Qualifikations-Checkliste (z. B. MEDDIC), bevor ein Deal zur Opportunity-Stage voranschreitet.',
      hint: 'Einbrüche bei Stage-Konversionsraten zeigen genau, wo der Vertriebsprozess zusammenbricht.',
    },
  },
];

export default questions;
