import type { QuizQuestion } from '@/content/types';

const questions: QuizQuestion[] = [
  {
    id: 'qq-planning-01',
    category: 'planning',
    conceptId: 'territory-design',
    question: 'What are the two primary territory design models used to divide a total addressable market among AEs?',
    options: [
      'Vertical and horizontal segmentation',
      'Geographic and named account',
      'Enterprise and mid-market split',
      'Top-down and bottom-up allocation',
    ],
    correctIndex: 1,
    explanation: 'The two primary models are geographic (AE owns all accounts in a region) and named account (AE owns a defined list regardless of location). Each has trade-offs around fairness, coverage, and AE specialisation.',
    difficulty: 'easy',
    de: {
      question: 'Was sind die zwei primären Territory-Design-Modelle zur Aufteilung eines adressierbaren Gesamtmarkts unter AEs?',
      options: [
        'Vertikale und horizontale Segmentierung',
        'Geografisch und Named Account',
        'Enterprise- und Mid-Market-Aufteilung',
        'Top-down und Bottom-up Zuteilung',
      ],
      explanation: 'Die zwei primären Modelle sind geografisch (der AE betreut alle Accounts in einer Region) und Named Account (der AE betreut eine definierte Liste unabhängig vom Standort). Jedes hat Kompromisse in Bezug auf Fairness, Abdeckung und AE-Spezialisierung.',
    },
  },
  {
    id: 'qq-planning-02',
    category: 'planning',
    conceptId: 'quota-setting',
    question: 'According to quota-setting best practice, what percentage of AEs hitting their quota indicates a healthy quota level?',
    options: [
      '40–50% of the team',
      '50–60% of the team',
      '60–70% of the team',
      '75–85% of the team',
    ],
    correctIndex: 2,
    explanation: 'A healthy quota should be achievable by 60–70% of the team. If everyone hits it the quota is too low and leaves revenue on the table; if fewer than 40% hit it the quota is too high and will drive attrition.',
    difficulty: 'easy',
    de: {
      question: 'Welcher Prozentsatz der AEs, die ihre Quote erreichen, zeigt laut Best Practice ein gesundes Quotenniveau an?',
      options: [
        '40–50 % des Teams',
        '50–60 % des Teams',
        '60–70 % des Teams',
        '75–85 % des Teams',
      ],
      explanation: 'Eine gesunde Quote sollte von 60–70 % des Teams erreichbar sein. Wenn alle sie erreichen, ist sie zu niedrig und lässt Umsatz liegen; wenn weniger als 40 % sie erreichen, ist sie zu hoch und führt zu Abgängen.',
    },
  },
  {
    id: 'qq-planning-03',
    category: 'planning',
    conceptId: 'capacity-models',
    question: 'What is the primary output of a sales capacity model?',
    options: [
      'A list of target accounts ranked by ARR potential',
      'A quarter-by-quarter headcount plan showing when to hire and with what profile',
      'A commission rate schedule for fully-ramped AEs',
      'A win-rate benchmark by vertical for the planning period',
    ],
    correctIndex: 1,
    explanation: 'A capacity model outputs a headcount plan by quarter showing when to hire, with what profile, and what cumulative ARR is projected given ramp curves and attrition. It also reveals the "productivity cliff" — the gap between current and needed headcount in any quarter.',
    difficulty: 'easy',
    de: {
      question: 'Was ist das primäre Ergebnis eines Sales-Kapazitätsmodells?',
      options: [
        'Eine Liste von Ziel-Accounts, gerankt nach ARR-Potenzial',
        'Ein quartalsweiser Headcount-Plan, der zeigt, wann und mit welchem Profil eingestellt werden muss',
        'Ein Provisionssatzsystem für voll eingearbeitete AEs',
        'Eine Win-Rate-Benchmark nach Vertikale für den Planungszeitraum',
      ],
      explanation: 'Ein Kapazitätsmodell liefert einen Headcount-Plan nach Quartal, der zeigt, wann und mit welchem Profil eingestellt werden muss, und welches kumulierte ARR bei gegebenen Hochlaufkurven und Fluktuationsraten projiziert wird. Es zeigt auch die "Produktivitätslücke" — den Abstand zwischen aktuellem und benötigtem Headcount in einem Quartal.',
    },
  },
  {
    id: 'qq-planning-04',
    category: 'planning',
    conceptId: 'ote-accelerators',
    question: 'What is the typical base/variable OTE split for enterprise SaaS AEs?',
    options: [
      '70/30 — higher base to reflect long sales cycles',
      '60/40 — moderate variable to limit risk for new hires',
      '50/50 — equal base and target variable',
      '40/60 — higher variable to maximise performance upside',
    ],
    correctIndex: 2,
    explanation: 'The standard enterprise SaaS split is 50/50 — equal base salary and target variable. More senior roles shift toward 60/40. A 50/50 split signals that hitting quota doubles the base, creating a strong performance incentive while still providing income security.',
    difficulty: 'easy',
    de: {
      question: 'Was ist die typische Basis-/Variabel-OTE-Aufteilung für Enterprise-SaaS-AEs?',
      options: [
        '70/30 — höheres Grundgehalt als Ausgleich für lange Sales-Zyklen',
        '60/40 — moderates Variables, um das Risiko für neue Mitarbeitende zu begrenzen',
        '50/50 — gleiches Grundgehalt und variables Zielgehalt',
        '40/60 — höheres Variables zur Maximierung des Performance-Upside',
      ],
      explanation: 'Die Standard-Aufteilung im Enterprise SaaS beträgt 50/50 — gleiches Grundgehalt und variables Zielgehalt. Erfahrenere Rollen verschieben sich zu 60/40. Eine 50/50-Aufteilung signalisiert, dass das Erreichen der Quote das Grundgehalt verdoppelt, was einen starken Leistungsanreiz schafft und gleichzeitig Einkommenssicherheit bietet.',
    },
  },
  {
    id: 'qq-planning-05',
    category: 'planning',
    conceptId: 'bottom-up-planning',
    question: 'What distinguishes a bottom-up plan from a top-down plan in revenue planning?',
    options: [
      'Bottom-up uses historical actuals; top-down uses analyst forecasts',
      'Bottom-up starts from individual territory assumptions and aggregates up; top-down divides a company target among reps',
      'Bottom-up is used only for new markets; top-down is used for mature markets',
      'Bottom-up sets the aspiration target; top-down reveals the achievable baseline',
    ],
    correctIndex: 1,
    explanation: 'Bottom-up planning starts from individual account or territory-level assumptions (TAM, ICP density, ACV, win rate, cycle length) and aggregates to a total. Top-down divides a company or board-level target among reps. Best practice is to run both and reconcile the gap — top-down sets ambition, bottom-up reveals reality.',
    hint: 'Think about where each approach starts: field data vs. company target.',
    difficulty: 'medium',
    de: {
      question: 'Was unterscheidet einen Bottom-up-Plan von einem Top-down-Plan in der Umsatzplanung?',
      options: [
        'Bottom-up nutzt historische Istwerte; Top-down nutzt Analystenprognosen',
        'Bottom-up beginnt mit individuellen Territoriums-Annahmen und aggregiert nach oben; Top-down verteilt ein Unternehmensziel auf die Reps',
        'Bottom-up wird nur für neue Märkte verwendet; Top-down für reife Märkte',
        'Bottom-up setzt das Ambitionsziel; Top-down zeigt die erreichbare Basis',
      ],
      explanation: 'Bottom-up-Planung beginnt mit Annahmen auf Einzel-Account- oder Territoriums-Ebene (TAM, ICP-Dichte, ACV, Win Rate, Zyklendauer) und aggregiert zu einem Gesamtziel. Top-down verteilt ein Unternehmens- oder Vorstandsziel auf die Reps. Best Practice ist, beide durchzuführen und die Lücke abzustimmen — Top-down setzt den Ehrgeiz, Bottom-up zeigt die Realität.',
      hint: 'Denken Sie daran, wo jeder Ansatz beginnt: Felddaten vs. Unternehmensziel.',
    },
  },
  {
    id: 'qq-planning-06',
    category: 'planning',
    conceptId: 'ote-accelerators',
    question: 'What is an accelerator in a sales compensation plan?',
    options: [
      'A ramp-up reduction that lets new AEs hit full quota faster',
      'A commission multiplier that kicks in above 100% quota attainment',
      'A quarterly bonus paid for early pipeline creation',
      'A base salary increase triggered by two consecutive quarters of quota attainment',
    ],
    correctIndex: 1,
    explanation: 'Accelerators are commission multipliers that activate above 100% quota attainment — for example, 1.5x commission on every dollar above quota, and 2.0x above 125%. They encourage AEs to push past quota rather than stop at 100% or sandbag.',
    difficulty: 'easy',
    de: {
      question: 'Was ist ein Accelerator in einem Vertriebsvergütungsplan?',
      options: [
        'Eine Verkürzung der Hochlaufphase, die neuen AEs hilft, schneller die volle Quote zu erreichen',
        'Ein Provisionsmultiplikator, der ab 100 % Quotenerreichung greift',
        'Ein Quartalsbonus für frühzeitige Pipeline-Erstellung',
        'Eine Grundgehaltserhöhung, die durch zwei aufeinanderfolgende Quartale mit Quotenerreichung ausgelöst wird',
      ],
      explanation: 'Acceleratoren sind Provisionsmultiplikatoren, die ab 100 % Quotenerreichung aktiviert werden — z. B. 1,5-fache Provision auf jeden Euro über der Quote und 2,0-fach über 125 %. Sie motivieren AEs, über die Quote hinaus zu pushen, statt bei 100 % zu stoppen oder zu sandbaggen.',
    },
  },
  {
    id: 'qq-planning-07',
    category: 'planning',
    conceptId: 'quota-setting',
    question: 'You observe that 60% of your DACH AEs missed quota last year and the miss is spread evenly across the whole team. What does this most likely indicate?',
    options: [
      'Two or three underperforming AEs are skewing the team average',
      'The quota was set too high — likely a market, capacity, or ramp calibration problem',
      'Pipeline coverage was insufficient and a coaching intervention is needed',
      'The territory split was unfair and should be redesigned before adjusting quota',
    ],
    correctIndex: 1,
    explanation: 'When a miss is concentrated in one or two reps it usually signals an individual performance issue. When the miss is spread evenly across the whole team it almost certainly means the quota itself was too high. The healthy miss rate is 30–40%; a team-wide 60% miss rate points to a systemic quota calibration problem.',
    hint: 'Ask yourself: concentrated miss vs. distributed miss — what does each pattern tell you?',
    difficulty: 'medium',
    de: {
      question: 'Sie beobachten, dass 60 % Ihrer DACH-AEs letztes Jahr ihre Quote verfehlt haben, und die Verfehlung ist gleichmäßig über das gesamte Team verteilt. Was deutet das am wahrscheinlichsten an?',
      options: [
        'Zwei oder drei schwache AEs verzerren den Teamdurchschnitt',
        'Die Quote war zu hoch gesetzt — wahrscheinlich ein Markt-, Kapazitäts- oder Hochlaufphasen-Kalibrierungsproblem',
        'Die Pipeline-Abdeckung war unzureichend und ein Coaching-Eingriff ist erforderlich',
        'Die Territoriumsaufteilung war unfair und sollte vor der Quotenanpassung überarbeitet werden',
      ],
      explanation: 'Wenn die Verfehlung bei ein oder zwei Reps konzentriert ist, signalisiert das in der Regel ein individuelles Performance-Problem. Wenn die Verfehlung gleichmäßig über das gesamte Team verteilt ist, bedeutet das fast sicher, dass die Quote selbst zu hoch war. Die gesunde Verfehlerquote beträgt 30–40 %; eine teamweite 60%-Verfehlung weist auf ein systemisches Quotenkalibrierungsproblem hin.',
      hint: 'Fragen Sie sich: konzentrierte Verfehlung vs. verteilte Verfehlung — was verrät Ihnen jedes Muster?',
    },
  },
  {
    id: 'qq-planning-08',
    category: 'planning',
    conceptId: 'comp-philosophy',
    question: 'Which of the following is identified as the most important principle of a sound comp plan philosophy?',
    options: [
      'Maximising total variable payout to attract top talent',
      'Aligning comp mechanics to the company\'s strategic priorities, not just revenue',
      'Ensuring the comp plan is updated at least twice per year to stay current',
      'Keeping base salary competitive with the top quartile of the market',
    ],
    correctIndex: 1,
    explanation: 'The core principle is alignment — the plan should reward the behaviours that drive company strategy, not just raw revenue. A plan that technically optimises the right metrics but that AEs do not understand will underperform a simpler, fair, and intuitive plan. Simplicity, fairness, and predictability round out the four core principles.',
    hint: 'The four principles are simplicity, alignment, fairness, and predictability — which is the most strategic?',
    difficulty: 'medium',
    de: {
      question: 'Welches der folgenden Prinzipien wird als das wichtigste einer soliden Vergütungsplan-Philosophie identifiziert?',
      options: [
        'Maximierung der variablen Gesamtauszahlung, um Top-Talente anzuziehen',
        'Ausrichtung der Vergütungsmechanik auf die strategischen Prioritäten des Unternehmens, nicht nur auf den Umsatz',
        'Sicherstellung, dass der Vergütungsplan mindestens zweimal pro Jahr aktualisiert wird',
        'Wettbewerbsfähiges Grundgehalt im oberen Quartil des Marktes',
      ],
      explanation: 'Das Kernprinzip ist Ausrichtung — der Plan sollte die Verhaltensweisen belohnen, die die Unternehmensstrategie fördern, nicht nur den reinen Umsatz. Ein Plan, der technisch die richtigen Kennzahlen optimiert, aber von AEs nicht verstanden wird, wird einen einfacheren, fairen und intuitiven Plan unterperformen. Einfachheit, Fairness und Vorhersehbarkeit runden die vier Kernprinzipien ab.',
      hint: 'Die vier Prinzipien sind Einfachheit, Ausrichtung, Fairness und Vorhersehbarkeit — welches ist das strategischste?',
    },
  },
  {
    id: 'qq-planning-09',
    category: 'planning',
    conceptId: 'capacity-models',
    question: 'Your capacity model projects €5.5M ARR achievable for DACH next year, but Finance has set the target at €8M. What is the recommended approach?',
    options: [
      'Accept the €8M target and distribute the difference equally across all AEs as a stretch quota',
      'Present the €5.5M model transparently, show what it would take to hit €8M, and propose a base/stretch structure',
      'Revise the win-rate assumption upward to bring the model in line with the Finance target',
      'Request a budget freeze until Finance reduces the target to match the achievable plan',
    ],
    correctIndex: 1,
    explanation: 'The right approach is to present the model transparently — never massage numbers to match a finance target. Show the assumptions that drive €5.5M, quantify exactly what investments (headcount, win-rate improvement, ACV uplift) would be needed to reach €8M, and propose €5.5M as the base case with a stretch target tied to specific conditions. This is a finance partnership conversation, not a negotiation.',
    hint: 'Consider what a credible, data-driven response looks like — neither pure capitulation nor flat refusal.',
    difficulty: 'medium',
    de: {
      question: 'Ihr Kapazitätsmodell projiziert €5,5M erreichbaren ARR für DACH im nächsten Jahr, aber Finance hat das Ziel auf €8M festgesetzt. Was ist der empfohlene Ansatz?',
      options: [
        'Das €8M-Ziel akzeptieren und die Differenz gleichmäßig auf alle AEs als Stretch-Quote verteilen',
        'Das €5,5M-Modell transparent präsentieren, zeigen was es braucht um €8M zu erreichen, und eine Basis-/Stretch-Struktur vorschlagen',
        'Die Win-Rate-Annahme nach oben revidieren, um das Modell an das Finance-Ziel anzupassen',
        'Einen Budget-Freeze beantragen, bis Finance das Ziel auf den erreichbaren Plan reduziert',
      ],
      explanation: 'Der richtige Ansatz ist, das Modell transparent zu präsentieren — niemals Zahlen verbiegen, um einem Finance-Ziel zu entsprechen. Die Annahmen, die €5,5M treiben, zeigen, genau quantifizieren, welche Investitionen (Headcount, Win-Rate-Verbesserung, ACV-Steigerung) benötigt würden, um €8M zu erreichen, und €5,5M als Basis-Szenario mit einem an spezifische Bedingungen geknüpften Stretch-Ziel vorschlagen. Das ist ein Finance-Partnerschaftsgespräch, keine Verhandlung.',
      hint: 'Überlegen Sie, wie eine glaubwürdige, datengetriebene Antwort aussieht — weder pure Kapitulation noch pauschale Ablehnung.',
    },
  },
  {
    id: 'qq-planning-10',
    category: 'planning',
    conceptId: 'ote-accelerators',
    question: 'What is the root cause of AE sandbagging — deliberately delaying deals to avoid over-attaining quota?',
    options: [
      'Poorly designed SPIF programmes that reward volume over deal quality',
      'Ratcheting quota mechanics where strong performance in one year raises the following year\'s quota',
      'A 50/50 base-variable split that makes the variable component feel too risky',
      'Insufficient pipeline coverage, leading AEs to hoard the deals they do have',
    ],
    correctIndex: 1,
    explanation: 'Sandbagging is a rational response to ratcheting quota mechanics — if 150% attainment this year leads to a proportionally higher quota next year, AEs rationally avoid over-attaining. The fix is credible quota-setting: cap year-over-year quota increases at a fixed percentage regardless of attainment (e.g., max 15%), so that high performance is not penalised.',
    hint: 'Think about what incentive structure makes it rational for an AE to hold back a deal.',
    difficulty: 'hard',
    de: {
      question: 'Was ist die Grundursache von AE-Sandbagging — dem absichtlichen Verzögern von Deals, um eine Übererfüllung der Quote zu vermeiden?',
      options: [
        'Schlecht gestaltete SPIF-Programme, die Volumen über Deal-Qualität stellen',
        'Ratcheting-Quotenmechaniken, bei denen starke Performance in einem Jahr die Quote des Folgejahres erhöht',
        'Eine 50/50-Basis-Variabel-Aufteilung, die die variable Komponente zu risikoreich erscheinen lässt',
        'Unzureichende Pipeline-Abdeckung, die AEs dazu bringt, ihre vorhandenen Deals zu horten',
      ],
      explanation: 'Sandbagging ist eine rationale Reaktion auf Ratcheting-Quotenmechaniken — wenn 150 % Erreichung in diesem Jahr zu einer proportional höheren Quote im nächsten Jahr führt, vermeiden AEs rational eine Übererfüllung. Die Lösung ist glaubwürdige Quotenfestlegung: Quotenerhöhungen von Jahr zu Jahr auf einen festen Prozentsatz deckeln (z. B. max. 15 %), unabhängig von der Erreichung, damit hohe Leistung nicht bestraft wird.',
      hint: 'Denken Sie darüber nach, welche Anreizstruktur es für einen AE rational macht, einen Deal zurückzuhalten.',
    },
  },
  {
    id: 'qq-planning-11',
    category: 'planning',
    conceptId: 'territory-design',
    question: 'A global enterprise account has its HQ in Munich but makes AI purchasing decisions in its Swiss and UK subsidiaries. Which territory design approach is recommended at an early-stage DACH team size?',
    options: [
      'Split the account between three regional AEs — DACH, UK, and a neutral coordinator — to maximise coverage',
      'Assign the account entirely to one AE (likely the DACH AE given Munich HQ) with a formal global coordination process',
      'Escalate to a global accounts team immediately, regardless of team size',
      'Leave the account unassigned until the decision-making entity is confirmed in writing',
    ],
    correctIndex: 1,
    explanation: 'For a smaller DACH team, the recommended approach is to assign the global account to a single AE — typically the DACH AE given the Munich HQ — while building a formal coordination process for subsidiary interactions. Splitting ownership across regional AEs creates comp conflict risk. The decision, including who receives credit for subsidiary deals, must be documented in CRM and signed off by sales leadership before any deal closes.',
    hint: 'Internal conflict and ambiguity are bigger risks than coverage gaps at this team size.',
    difficulty: 'medium',
    de: {
      question: 'Ein globaler Enterprise-Account hat seinen Hauptsitz in München, trifft aber KI-Kaufentscheidungen in seinen Schweizer und britischen Tochtergesellschaften. Welcher Territory-Design-Ansatz wird für ein frühphasiges DACH-Team empfohlen?',
      options: [
        'Den Account auf drei regionale AEs aufteilen — DACH, UK und einen neutralen Koordinator — um maximale Abdeckung zu gewährleisten',
        'Den Account einem einzigen AE zuweisen (wahrscheinlich dem DACH-AE aufgrund des Münchner Hauptsitzes) mit einem formalen globalen Koordinationsprozess',
        'Sofort an ein Global-Accounts-Team eskalieren, unabhängig von der Teamgröße',
        'Den Account unzugewiesen lassen, bis die Entscheidungsinstanz schriftlich bestätigt ist',
      ],
      explanation: 'Für ein kleineres DACH-Team ist der empfohlene Ansatz, den globalen Account einem einzigen AE zuzuweisen — typischerweise dem DACH-AE aufgrund des Münchner Hauptsitzes — während ein formaler Koordinationsprozess für Tochtergesellschaften aufgebaut wird. Eine Aufspaltung der Verantwortung auf regionale AEs schafft Vergütungskonfliktrisiken. Die Entscheidung, einschließlich wer für Tochtergesellschafts-Deals Provision erhält, muss im CRM dokumentiert und von der Vertriebsleitung abgezeichnet werden, bevor ein Deal abgeschlossen wird.',
      hint: 'Interne Konflikte und Unklarheiten sind bei dieser Teamgröße größere Risiken als Abdeckungslücken.',
    },
  },
  {
    id: 'qq-planning-12',
    category: 'planning',
    conceptId: 'comp-philosophy',
    question: 'A comp plan commissions AEs on year-1 ACV only, causing them to avoid multi-year deals. Beyond a plan redesign, what immediate corrective action is required for AEs who already closed multi-year deals under the flawed plan?',
    options: [
      'Issue a written apology and promise to correct the plan before next fiscal year',
      'Retroactively credit those AEs on the full TCV of their multi-year deals, not just year 1',
      'Offer a one-time SPIF payment equal to 10% of the year-2 and year-3 contract value',
      'Allow affected AEs to re-negotiate their quota downward to compensate for the lost commission',
    ],
    correctIndex: 1,
    explanation: 'The immediate corrective action is to retroactively credit AEs who closed multi-year deals on the full TCV (total contract value), not just year 1. Failing to do so punishes AEs for behaving in the company\'s best interest under a plan that was the manager\'s error. Transparency about the mistake and prompt remediation is essential to preserving trust — the most valuable long-term asset in comp management.',
    hint: 'Fairness principle: AEs should not be penalised for a comp design error they did not cause.',
    difficulty: 'hard',
    de: {
      question: 'Ein Vergütungsplan zahlt AEs Provision nur auf den Jahr-1-ACV, was dazu führt, dass sie Multi-Year-Deals vermeiden. Welche sofortige Korrekturmaßnahme ist — neben einer Plan-Neugestaltung — für AEs erforderlich, die bereits Multi-Year-Deals unter dem fehlerhaften Plan abgeschlossen haben?',
      options: [
        'Eine schriftliche Entschuldigung ausstellen und versprechen, den Plan vor dem nächsten Geschäftsjahr zu korrigieren',
        'Diesen AEs rückwirkend auf Basis des gesamten TCV ihrer Multi-Year-Deals gutschreiben, nicht nur Jahr 1',
        'Eine einmalige SPIF-Zahlung von 10 % des Jahr-2- und Jahr-3-Vertragswerts anbieten',
        'Betroffenen AEs erlauben, ihre Quote nach unten neu zu verhandeln, um die entgangene Provision auszugleichen',
      ],
      explanation: 'Die sofortige Korrekturmaßnahme ist, AEs, die Multi-Year-Deals abgeschlossen haben, rückwirkend auf Basis des gesamten TCV (Gesamtvertragswert), nicht nur Jahr 1, gutzuschreiben. Dies zu unterlassen bestraft AEs dafür, im besten Interesse des Unternehmens unter einem Plan gehandelt zu haben, der ein Führungsfehler war. Transparenz über den Fehler und schnelle Abhilfe sind unerlässlich, um Vertrauen zu erhalten — das wertvollste langfristige Kapital im Vergütungsmanagement.',
      hint: 'Fairness-Prinzip: AEs sollten nicht für einen Vergütungsdesignfehler bestraft werden, den sie nicht verursacht haben.',
    },
  },
];

export default questions;
