import type { QuizQuestion } from '@/content/types';

const questions: QuizQuestion[] = [
  {
    id: 'qq-revops-01',
    category: 'revops',
    conceptId: 'pipeline-management',
    question: 'What is the recommended pipeline coverage ratio for an enterprise AI software sale, and why is it higher than standard SaaS?',
    options: [
      '1.5–2x, because enterprise deals are more predictable',
      '2–2.5x, because standard SaaS benchmarks apply equally',
      '3–4x, because enterprise cycles run 6–9 months and deals stall frequently',
      '5–6x, because most enterprise AI deals never close',
    ],
    correctIndex: 2,
    explanation: 'Enterprise AI deals typically span 6–9 month cycles and frequently stall at security review or legal, requiring a 3–4x coverage buffer to ensure the quarter can still be made even if late-stage deals slip.',
    hint: 'Think about what happens when a €500K deal sits in security review for 8 weeks.',
    difficulty: 'easy',
    de: {
      question: 'Wie hoch ist die empfohlene Pipeline-Coverage-Ratio für einen Enterprise-KI-Software-Verkauf, und warum ist sie höher als bei Standard-SaaS?',
      options: [
        '1,5–2x, weil Enterprise-Deals vorhersehbarer sind',
        '2–2,5x, weil Standard-SaaS-Benchmarks gleichermaßen gelten',
        '3–4x, weil Enterprise-Zyklen 6–9 Monate dauern und Deals häufig stagnieren',
        '5–6x, weil die meisten Enterprise-KI-Deals nie abgeschlossen werden',
      ],
      explanation: 'Enterprise-KI-Deals erstrecken sich typischerweise über 6–9 Monatszyklen und stagnieren häufig beim Security-Review oder Rechtsteam. Daher wird ein Coverage-Puffer von 3–4x benötigt, um das Quartalsziel noch erreichen zu können, wenn Late-Stage-Deals rutschen.',
      hint: 'Denke daran, was passiert, wenn ein 500.000-€-Deal 8 Wochen lang beim Security-Review steckt.',
    },
  },
  {
    id: 'qq-revops-02',
    category: 'revops',
    conceptId: 'pipeline-management',
    question: 'During a pipeline review, you strip out all deals older than 90 days with no stage movement. What does this exercise reveal?',
    options: [
      'The total number of deals currently in negotiation',
      'Your real pipeline coverage after removing zombie deals',
      'Which AEs have the highest average deal size',
      'The win rate for deals that have been in the pipeline longest',
    ],
    correctIndex: 1,
    explanation: "Deals older than 90 days with no stage movement are zombie pipeline — they inflate coverage figures but have little realistic chance of closing. Removing them reveals your true, actionable coverage and prevents misleading forecasts.",
    hint: 'A deal that has not moved in 90 days is not the same as a live opportunity.',
    difficulty: 'medium',
    de: {
      question: 'Du filterst beim Pipeline-Review alle Deals heraus, die älter als 90 Tage sind und keine Phasenbewegung zeigen. Was zeigt diese Übung?',
      options: [
        'Die Gesamtzahl der Deals, die sich aktuell in Verhandlung befinden',
        'Deine echte Pipeline-Coverage nach dem Entfernen von Zombie-Deals',
        'Welche AEs den höchsten durchschnittlichen Deal-Wert haben',
        'Die Win-Rate für Deals, die sich am längsten in der Pipeline befinden',
      ],
      explanation: 'Deals, die seit mehr als 90 Tagen keine Phasenbewegung zeigen, sind Zombie-Pipeline — sie blähen die Coverage-Zahlen auf, haben aber kaum realistische Abschluss-Chancen. Ihre Entfernung zeigt die tatsächliche, handlungsfähige Coverage und verhindert irreführende Forecasts.',
      hint: 'Ein Deal, der sich seit 90 Tagen nicht bewegt hat, ist keine aktive Opportunity.',
    },
  },
  {
    id: 'qq-revops-03',
    category: 'revops',
    conceptId: 'forecasting',
    question: 'An enterprise sales team layers three forecasting methods: stage-weighted, call-based, and AI-assisted. What is the primary purpose of the AI-assisted layer?',
    options: [
      'To replace the AE commit call entirely with an objective number',
      'To detect patterns in activity signals that predict close probability',
      'To assign stage probabilities based on historical close rates',
      'To automate pipeline entry and remove manual CRM updates',
    ],
    correctIndex: 1,
    explanation: 'AI-assisted tools like Clari or Gong analyse activity signals — email response rates, call frequency, engagement scores — to identify patterns that predict whether a deal will close. They complement, rather than replace, the other two methods.',
    hint: 'Think about what Gong and Clari actually analyse.',
    difficulty: 'easy',
    de: {
      question: 'Ein Enterprise-Vertriebsteam schichtet drei Forecast-Methoden: phasengewichtet, call-basiert und KI-gestützt. Was ist der primäre Zweck der KI-gestützten Schicht?',
      options: [
        'Den AE-Commit-Call vollständig durch eine objektive Zahl zu ersetzen',
        'Muster in Aktivitätssignalen zu erkennen, die die Abschlusswahrscheinlichkeit vorhersagen',
        'Phasenwahrscheinlichkeiten auf Basis historischer Abschlussraten zuzuweisen',
        'Pipeline-Einträge zu automatisieren und manuelle CRM-Updates zu entfernen',
      ],
      explanation: 'KI-gestützte Tools wie Clari oder Gong analysieren Aktivitätssignale — E-Mail-Antwortraten, Gesprächshäufigkeit, Engagement-Scores — um Muster zu identifizieren, die vorhersagen, ob ein Deal abgeschlossen wird. Sie ergänzen die anderen zwei Methoden, ersetzen sie aber nicht.',
      hint: 'Überlege, was Gong und Clari tatsächlich analysieren.',
    },
  },
  {
    id: 'qq-revops-04',
    category: 'revops',
    conceptId: 'forecasting',
    question: 'A key limitation of stage-weighted forecasting is that it assigns the same probability to a deal regardless of how long it has been in that stage. What is the best compensating mechanism?',
    options: [
      'Increasing the stage probability weights across the board',
      'Adding age decay to reduce probability for deals that have not moved within a set number of days',
      'Removing all deals from the forecast that are older than 30 days',
      'Asking AEs to manually override every probability in the CRM',
    ],
    correctIndex: 1,
    explanation: 'Age decay reduces the forecast probability for deals that have not advanced within a defined window (e.g., 30 days). A stage-3 deal at day 180 with no movement is far less likely to close than a stage-3 deal at day 10, but raw stage-weighting treats them identically.',
    hint: 'The problem is that stage weights are static averages that ignore deal momentum.',
    difficulty: 'medium',
    de: {
      question: 'Eine zentrale Schwäche der phasengewichteten Forecasting-Methode ist, dass sie jedem Deal die gleiche Wahrscheinlichkeit zuweist, unabhängig davon, wie lange er bereits in dieser Phase ist. Was ist der beste Kompensationsmechanismus?',
      options: [
        'Die Phasenwahrscheinlichkeitsgewichte generell erhöhen',
        'Altersabfall (Age Decay) hinzufügen, um die Wahrscheinlichkeit für Deals zu reduzieren, die sich innerhalb einer definierten Anzahl von Tagen nicht bewegt haben',
        'Alle Deals, die älter als 30 Tage sind, aus dem Forecast entfernen',
        'AEs bitten, jede Wahrscheinlichkeit im CRM manuell zu überschreiben',
      ],
      explanation: 'Altersabfall reduziert die Forecast-Wahrscheinlichkeit für Deals, die sich innerhalb eines definierten Zeitfensters (z. B. 30 Tage) nicht weiterentwickelt haben. Ein Phase-3-Deal an Tag 180 ohne Bewegung hat eine deutlich geringere Abschlusswahrscheinlichkeit als ein Phase-3-Deal an Tag 10, aber die reine Phasengewichtung behandelt beide identisch.',
      hint: 'Das Problem ist, dass Phasengewichte statische Durchschnittswerte sind, die keine Deal-Dynamik berücksichtigen.',
    },
  },
  {
    id: 'qq-revops-05',
    category: 'revops',
    conceptId: 'crm-hygiene',
    question: 'When trying to improve CRM adoption, a RevOps leader should lead with AE self-interest rather than enforcement. Which argument best appeals to that self-interest?',
    options: [
      'Accurate CRM data allows leadership to monitor individual performance more closely',
      'Accurate CRM means a better forecast, which leads to less surprise at compensation time',
      'Completing CRM fields is required by the sales methodology and reduces audit risk',
      'Managers can only conduct pipeline reviews if every deal has full field completion',
    ],
    correctIndex: 1,
    explanation: "AEs are motivated by predictable compensation. When CRM data is accurate, forecasting improves, reducing the risk of unexpected quota adjustments or disputed attainment calculations. Framing CRM hygiene as a tool that protects the AE's own earnings is far more persuasive than framing it as a compliance requirement.",
    difficulty: 'easy',
    de: {
      question: 'Wenn ein RevOps-Leader die CRM-Adoption verbessern möchte, sollte er mit dem AE-Eigeninteresse beginnen, nicht mit Durchsetzung. Welches Argument spricht dieses Eigeninteresse am stärksten an?',
      options: [
        'Genaue CRM-Daten ermöglichen der Führung, die individuelle Leistung genauer zu überwachen',
        'Ein genaues CRM führt zu einem besseren Forecast, was zu weniger Überraschungen bei der Provisions-Abrechnung führt',
        'Das Ausfüllen von CRM-Feldern ist durch die Vertriebsmethodik vorgeschrieben und reduziert das Prüfungsrisiko',
        'Manager können Pipeline-Reviews nur durchführen, wenn alle Deals vollständig ausgefüllt sind',
      ],
      explanation: 'AEs sind durch vorhersehbare Vergütung motiviert. Wenn CRM-Daten akkurat sind, verbessert sich das Forecasting und das Risiko unerwarteter Quotenanpassungen oder bestrittener Erreichungsberechnungen sinkt. CRM-Hygiene als ein Tool zu framen, das das Einkommen des AEs schützt, ist weit überzeugender als eine Compliance-Anforderung.',
    },
  },
  {
    id: 'qq-revops-06',
    category: 'revops',
    conceptId: 'crm-hygiene',
    question: 'If you could enforce only five mandatory fields in Salesforce for an enterprise sales motion, which field is identified as the single most predictive of deal health — and which AEs most commonly skip?',
    options: [
      'Close date',
      'Deal stage',
      'Economic buyer (contact record)',
      'Competitor (if any)',
    ],
    correctIndex: 2,
    explanation: "Identifying the economic buyer is the single most predictive CRM field for deal health in enterprise sales. Without a named economic buyer attached to the opportunity, there is no confirmed path to a decision. It is also the field AEs most commonly skip because it requires discovery work they haven't done yet.",
    hint: 'Which field confirms there is a real decision-maker involved in the deal?',
    difficulty: 'medium',
    de: {
      question: 'Wenn du nur fünf Pflichtfelder in Salesforce für eine Enterprise-Vertriebsmotion durchsetzen könntest, welches Feld wird als das prädiktivste für die Deal-Gesundheit identifiziert — und welches überspringen AEs am häufigsten?',
      options: [
        'Close Date',
        'Deal-Phase',
        'Economic Buyer (Kontaktdatensatz)',
        'Wettbewerber (falls vorhanden)',
      ],
      explanation: 'Die Identifikation des Economic Buyers ist das einzeln prädiktivste CRM-Feld für die Deal-Gesundheit im Enterprise-Vertrieb. Ohne einen namentlich genannten Economic Buyer am Opportunity-Datensatz gibt es keinen bestätigten Weg zu einer Entscheidung. Es ist auch das Feld, das AEs am häufigsten überspringen, weil es Discovery-Arbeit erfordert, die sie noch nicht geleistet haben.',
      hint: 'Welches Feld bestätigt, dass ein echter Entscheider in den Deal involviert ist?',
    },
  },
  {
    id: 'qq-revops-07',
    category: 'revops',
    conceptId: 'sales-tech-stack',
    question: 'When building out a sales tech stack for a new 15-person enterprise team, what is the correct sequencing priority?',
    options: [
      'Conversation intelligence first, then CRM, then sales engagement platform',
      'BI and reporting first, so leadership has visibility before anything else',
      'CRM first as the system of record, then sales engagement platform, then conversation intelligence',
      'CPQ and quoting tools first to accelerate deal velocity from day one',
    ],
    correctIndex: 2,
    explanation: 'CRM must come first because it is the system of record that all other tools depend on. Without clean CRM data, a sales engagement platform has no account data to sequence against, and conversation intelligence has no deals to score. Adding complexity before the CRM foundation is clean creates compounding data problems.',
    difficulty: 'easy',
    de: {
      question: 'Beim Aufbau eines Sales Tech Stacks für ein neues 15-köpfiges Enterprise-Team — was ist die richtige Priorisierungsreihenfolge?',
      options: [
        'Zuerst Conversation Intelligence, dann CRM, dann Sales Engagement Platform',
        'Zuerst BI und Reporting, damit die Führung Transparenz hat, bevor alles andere kommt',
        'Zuerst CRM als System of Record, dann Sales Engagement Platform, dann Conversation Intelligence',
        'Zuerst CPQ- und Angebots-Tools, um die Deal-Velocity von Anfang an zu beschleunigen',
      ],
      explanation: 'Das CRM muss zuerst kommen, da es das System of Record ist, von dem alle anderen Tools abhängen. Ohne saubere CRM-Daten hat eine Sales Engagement Platform keine Account-Daten für Sequenzen, und Conversation Intelligence hat keine Deals zum Bewerten. Komplexität hinzuzufügen, bevor das CRM-Fundament sauber ist, erzeugt sich verstärkende Datenprobleme.',
    },
  },
  {
    id: 'qq-revops-08',
    category: 'revops',
    conceptId: 'sales-tech-stack',
    question: 'You have just rolled out Gong to your enterprise team. At the 90-day mark, which outcome best defines a successful rollout — beyond just recording calls?',
    options: [
      'Over 90% of calls are recorded and stored in the Gong archive',
      'Gong is integrated into weekly deal reviews and managers use it for active coaching',
      'AEs have completed the onboarding training and can log calls independently',
      'The IT team has confirmed stable integration with Salesforce and Outlook',
    ],
    correctIndex: 1,
    explanation: "Recording calls is just the first step. Gong's value comes from managers using call recordings in weekly deal reviews to coach on objection handling, competitive positioning, and deal progression. If Gong is just a recording archive that nobody opens, the rollout has failed on the outcomes that matter.",
    hint: "Think about what separates a tool that's 'adopted' from one that's genuinely used.",
    difficulty: 'medium',
    de: {
      question: 'Du hast gerade Gong für dein Enterprise-Team eingeführt. Was definiert nach 90 Tagen am besten einen erfolgreichen Rollout — über das bloße Aufzeichnen von Gesprächen hinaus?',
      options: [
        'Über 90% der Gespräche werden aufgezeichnet und im Gong-Archiv gespeichert',
        'Gong ist in wöchentliche Deal-Reviews integriert und Manager nutzen es aktiv für Coaching',
        'AEs haben das Onboarding-Training abgeschlossen und können Gespräche selbstständig protokollieren',
        'Das IT-Team hat eine stabile Integration mit Salesforce und Outlook bestätigt',
      ],
      explanation: "Das Aufzeichnen von Gesprächen ist nur der erste Schritt. Gongs Wert entsteht dadurch, dass Manager Gesprächsaufzeichnungen in wöchentlichen Deal-Reviews nutzen, um Einwandbehandlung, Wettbewerbspositionierung und Deal-Fortschritt zu coachen. Wenn Gong nur ein Aufzeichnungsarchiv ist, das niemand öffnet, ist der Rollout bei den wichtigen Outcomes gescheitert.",
      hint: "Überlege, was ein 'adoptiertes' Tool von einem wirklich genutzten unterscheidet.",
    },
  },
  {
    id: 'qq-revops-09',
    category: 'revops',
    conceptId: 'lead-routing',
    question: 'A developer at a €2B German manufacturing firm submits a form expressing interest in the Claude API. What is the correct routing decision?',
    options: [
      'Send an automated developer API sequence immediately, as the form signals API intent',
      'Route to the SMB team because the contact is an individual developer, not an executive',
      'Treat the company size as an enterprise signal, enrich the lead, and route to the DACH AE responsible for that account',
      'Hold the lead until a senior executive from the same company submits a separate form',
    ],
    correctIndex: 2,
    explanation: "The form fill signals API curiosity, but the company (€2B German manufacturer) is a clear enterprise signal that overrides the stated intent. Lead enrichment should confirm firmographic data, check if a DACH AE already owns the account, and route accordingly. Sending an automated developer sequence to a €2B enterprise is a missed opportunity.",
    hint: 'Which signal matters more for routing: what the person said on the form, or who they work for?',
    difficulty: 'medium',
    de: {
      question: 'Ein Entwickler eines deutschen Fertigungsunternehmens mit 2 Mrd. € Umsatz reicht ein Formular ein und bekundet Interesse an der Claude API. Was ist die richtige Routing-Entscheidung?',
      options: [
        'Sofort eine automatisierte Developer-API-Sequenz versenden, da das Formular API-Interesse signalisiert',
        'An das SMB-Team weiterleiten, weil der Kontakt ein einzelner Entwickler ist, kein Führungskraft',
        'Die Unternehmensgröße als Enterprise-Signal behandeln, den Lead anreichern und an den DACH-AE weiterleiten, der für diesen Account verantwortlich ist',
        'Den Lead zurückhalten, bis eine Führungskraft desselben Unternehmens ein separates Formular einreicht',
      ],
      explanation: 'Das Formular signalisiert API-Neugier, aber das Unternehmen (2 Mrd. € deutsches Fertigungsunternehmen) ist ein klares Enterprise-Signal, das die angegebene Absicht überschreibt. Die Lead-Anreicherung sollte firmografische Daten bestätigen, prüfen ob ein DACH-AE diesen Account bereits besitzt, und entsprechend weiterleiten. Eine automatisierte Developer-Sequenz an ein 2-Mrd.-€-Unternehmen zu schicken ist eine verpasste Opportunity.',
      hint: 'Welches Signal ist für das Routing wichtiger: was die Person auf dem Formular angegeben hat, oder für wen sie arbeitet?',
    },
  },
  {
    id: 'qq-revops-10',
    category: 'revops',
    conceptId: 'lead-routing',
    question: 'In Anthropic\'s DACH market, the dual API and enterprise motion requires routing leads into two distinct tracks. What is the primary signal used to route a lead into the enterprise AE track rather than the developer/PLG track?',
    options: [
      'The lead mentions a specific use case involving large language models',
      'The lead\'s job title contains the word "engineer" or "developer"',
      'The company has over 500 employees, operates in a strategic industry, and the contact holds a senior title such as CDO or CTO',
      'The lead clicked on a paid ad rather than arriving via organic search',
    ],
    correctIndex: 2,
    explanation: 'Enterprise routing is triggered by firmographic and role signals: company size above 500 employees, a strategic industry (financial services, healthcare, technology), and a senior decision-maker title. These signals indicate potential for a structured enterprise deal. A developer job title, regardless of company size, would default to the PLG track without these confirmations.',
    hint: 'Think about the three types of data that define whether a company is enterprise-grade.',
    difficulty: 'hard',
    de: {
      question: 'In Anthropics DACH-Markt erfordert die duale API- und Enterprise-Motion, Leads in zwei verschiedene Tracks weiterzuleiten. Was ist das primäre Signal, um einen Lead in den Enterprise-AE-Track statt in den Developer/PLG-Track zu routen?',
      options: [
        'Der Lead erwähnt einen konkreten Anwendungsfall mit großen Sprachmodellen',
        'Der Jobtitel des Leads enthält das Wort "Engineer" oder "Developer"',
        'Das Unternehmen hat mehr als 500 Mitarbeiter, ist in einer strategischen Branche tätig, und der Kontakt hat einen leitenden Titel wie CDO oder CTO',
        'Der Lead hat auf eine bezahlte Anzeige geklickt statt über organische Suche zu kommen',
      ],
      explanation: 'Enterprise-Routing wird durch firmografische und Rollensignale ausgelöst: Unternehmensgröße über 500 Mitarbeiter, eine strategische Branche (Financial Services, Healthcare, Technologie) und ein leitender Entscheider-Titel. Diese Signale weisen auf das Potenzial für einen strukturierten Enterprise-Deal hin. Ein Developer-Jobtitel würde unabhängig von der Unternehmensgröße ohne diese Bestätigungen standardmäßig im PLG-Track landen.',
      hint: 'Überlege, welche drei Datentypen definieren, ob ein Unternehmen Enterprise-Charakter hat.',
    },
  },
  {
    id: 'qq-revops-11',
    category: 'revops',
    conceptId: 'revenue-analytics',
    question: 'When building a weekly pipeline dashboard from scratch, what is the critical distinction between a leading indicator and a lagging indicator?',
    options: [
      'Leading indicators are reported by AEs; lagging indicators are reported by finance',
      'Leading indicators predict future revenue (e.g., new pipeline created, stage conversion); lagging indicators measure revenue already recognised (e.g., closed-won, ACV)',
      'Leading indicators cover the current quarter; lagging indicators cover prior periods',
      'Leading indicators require clean CRM data; lagging indicators can be calculated from finance systems alone',
    ],
    correctIndex: 1,
    explanation: 'Leading indicators — pipeline coverage, new pipeline created, stage conversion rates, and activity levels — signal what revenue is likely to materialise in future periods and allow early intervention. Lagging indicators like closed-won revenue and ACV reflect what has already happened and cannot be changed. A useful dashboard includes both, but the leading indicators are what drive action.',
    hint: 'One type of metric lets you change the outcome; the other just records what happened.',
    difficulty: 'hard',
    de: {
      question: 'Beim Aufbau eines wöchentlichen Pipeline-Dashboards von Grund auf — was ist der entscheidende Unterschied zwischen einem vorlaufenden und einem nachlaufenden Indikator?',
      options: [
        'Vorlaufende Indikatoren werden von AEs gemeldet; nachlaufende Indikatoren werden von Finance gemeldet',
        'Vorlaufende Indikatoren sagen zukünftigen Umsatz vorher (z. B. neu erstellte Pipeline, Phasen-Conversion); nachlaufende Indikatoren messen bereits erfassten Umsatz (z. B. Closed-Won, ACV)',
        'Vorlaufende Indikatoren betreffen das laufende Quartal; nachlaufende Indikatoren betreffen vergangene Perioden',
        'Vorlaufende Indikatoren erfordern saubere CRM-Daten; nachlaufende Indikatoren können allein aus Finance-Systemen berechnet werden',
      ],
      explanation: 'Vorlaufende Indikatoren — Pipeline-Coverage, neu erstellte Pipeline, Phasen-Konversionsraten und Aktivitätsniveaus — signalisieren, welcher Umsatz in zukünftigen Perioden wahrscheinlich realisiert wird, und ermöglichen frühzeitiges Eingreifen. Nachlaufende Indikatoren wie Closed-Won-Umsatz und ACV spiegeln das bereits Geschehene wider und können nicht mehr verändert werden. Ein nützliches Dashboard enthält beide, aber die vorlaufenden Indikatoren sind es, die Maßnahmen antreiben.',
      hint: 'Eine Art Metrik ermöglicht es dir, das Ergebnis zu verändern; die andere zeichnet nur auf, was passiert ist.',
    },
  },
  {
    id: 'qq-revops-12',
    category: 'revops',
    conceptId: 'revenue-analytics',
    question: 'You join a DACH enterprise team that has Salesforce but inconsistent data and no reporting infrastructure. What is the correct first step before building any dashboards?',
    options: [
      'Connect Tableau or Looker to Salesforce and start building dashboards immediately',
      'Run a top-of-funnel inbound campaign to create more pipeline data to analyse',
      'Agree on metric definitions (e.g., what counts as a qualified opportunity, what counts as ARR) before touching any tool',
      'Ask leadership to pause all deal activity until the data quality issues are resolved',
    ],
    correctIndex: 2,
    explanation: 'Building dashboards before agreeing on definitions produces metrics that different stakeholders interpret differently, which destroys trust in the data. The first step is always to align on what each metric means — particularly terms like qualified opportunity, ARR, and pipeline stage — so that every report is built on a shared foundation.',
    hint: 'What happens if two people look at the same dashboard and disagree about what the numbers mean?',
    difficulty: 'hard',
    de: {
      question: 'Du trittst einem DACH-Enterprise-Team bei, das Salesforce hat, aber inkonsistente Daten und keine Reporting-Infrastruktur. Was ist der richtige erste Schritt, bevor Dashboards aufgebaut werden?',
      options: [
        'Tableau oder Looker sofort mit Salesforce verbinden und mit dem Dashboard-Aufbau beginnen',
        'Eine Top-of-Funnel-Inbound-Kampagne starten, um mehr Pipeline-Daten zur Analyse zu generieren',
        'Metrik-Definitionen vereinbaren (z. B. was als qualifizierte Opportunity gilt, was als ARR zählt), bevor ein Tool angefasst wird',
        'Die Führung bitten, alle Deal-Aktivitäten zu pausieren, bis die Datenqualitätsprobleme behoben sind',
      ],
      explanation: 'Dashboards aufzubauen, bevor Definitionen vereinbart wurden, produziert Metriken, die verschiedene Stakeholder unterschiedlich interpretieren, was das Vertrauen in die Daten zerstört. Der erste Schritt ist immer die Einigung darüber, was jede Metrik bedeutet — insbesondere Begriffe wie qualifizierte Opportunity, ARR und Pipeline-Phase — damit jeder Bericht auf einem gemeinsamen Fundament aufgebaut wird.',
      hint: 'Was passiert, wenn zwei Personen auf dasselbe Dashboard schauen und sich über die Bedeutung der Zahlen uneinig sind?',
    },
  },
];

export default questions;
