import type { Question } from "@/content/types";

const questions: Question[] = [
  {
    id: "rs-01",
    category: "role-specific",
    prompt:
      "How would you approach territory design for Anthropic's DACH enterprise segment? Walk me through your methodology.",
    difficulty: "hard",
    idealAnswerThemes: [
      "Start with TAM: total enterprise accounts in DACH that fit ICP",
      "ICP defined by firmographic signals, not just company size",
      "Geo vs. named account decision — make it explicit and justify it",
      "AE capacity model: how many accounts per fully-ramped AE",
      "Account tier logic: strategic vs. commercial vs. velocity",
      "Named accounts for top 20–30 strategic targets",
      "Review cycle: territory is a living design, not set-and-forget",
      "DACH nuance: DE vs. AT/CH distinction matters (language, regulation, market size)",
    ],
  },
  {
    id: "rs-02",
    category: "role-specific",
    prompt:
      "How would you build a quota model for a new enterprise AE joining the DACH team?",
    difficulty: "hard",
    idealAnswerThemes: [
      "Ramp timeline: months 1–3 at 25–50%, months 4–6 at 75%, full quota by month 7",
      "Bottoms-up methodology: territory TAM × win rate × expected ACV",
      "Sanity-check against top-down company target",
      "Fairness test: is this achievable for a strong AE?",
      "60–70% of team should hit quota in a well-calibrated model",
      "Account for deal cycle length — DACH enterprise is 6–12 months",
      "First-year quota explicitly lower to account for pipeline build",
      "Over-quota recourse: accelerators, not just cash, matter for retention",
    ],
  },
  {
    id: "rs-03",
    category: "role-specific",
    prompt:
      "What does a healthy pipeline look like for an enterprise AI software sale in DACH? What coverage ratio would you target?",
    difficulty: "medium",
    idealAnswerThemes: [
      "3–4x coverage ratio for enterprise (higher than typical SaaS due to long cycles)",
      "Stage distribution matters as much as total coverage",
      "Watch for pipeline concentration risk (few large deals = volatile forecast)",
      "Source mix: outbound, inbound, partner — no single-source dependency",
      "Age by stage: stale deals are phantom pipeline",
      "DACH-specific: 6–9 month average cycle → Q1 pipeline built in Q3 prior year",
      "POC conversion rate as a leading indicator of pipeline quality",
      "Separate new logo pipeline from expansion pipeline",
    ],
  },
  {
    id: "rs-04",
    category: "role-specific",
    prompt:
      "If pipeline in DACH financial services is underperforming at mid-quarter, what is your diagnostic process?",
    difficulty: "hard",
    idealAnswerThemes: [
      "Diagnose before prescribing — don't assume the cause",
      "Layer 1: coverage check — is total pipeline below 3x?",
      "Layer 2: stage distribution — where are deals concentrating or dying?",
      "Layer 3: source check — is inbound drying up or is outbound not converting?",
      "Layer 4: competitive signals — are we losing to a specific competitor?",
      "Layer 5: AE-level analysis — is it one rep or systemic?",
      "Immediate actions vs. structural fixes — quarter vs. half fixes",
      "Pipeline creation sprint: events, outbound blitz, partner co-sell",
    ],
  },
  {
    id: "rs-05",
    category: "role-specific",
    prompt:
      "How would you prioritize which verticals to focus on first in DACH for Anthropic's enterprise motion?",
    difficulty: "hard",
    idealAnswerThemes: [
      "Scoring matrix: market size × ICP density × deal velocity × Claude fit × regulatory environment",
      "FS: highest ACV, strongest Claude differentiation (safety + long-context), slowest cycles",
      "Technology: fastest cycles, technical buyers who can self-evaluate, lower ACV",
      "Healthcare: strong use case fit but strict data-residency requirements",
      "Manufacturing/Mittelstand: large market but early-stage AI adoption, longer sales education",
      "Existing Anthropic case studies in each vertical — anchor with proof",
      "Year 1: FS + Technology as primary; Healthcare as secondary",
      "Avoid spreading too thin — depth in 2 verticals beats breadth in 5",
    ],
  },
  {
    id: "rs-06",
    category: "role-specific",
    prompt:
      "Walk me through how you'd design a sales play for the financial services vertical in DACH.",
    difficulty: "hard",
    idealAnswerThemes: [
      "Trigger: bank/insurer launching or scaling a GenAI initiative",
      "Persona: CDO or Chief Risk Officer — not just CTO",
      "Hook: safety compliance + regulatory defensibility (BaFin, EU AI Act)",
      "Specific use case anchor: regulatory reporting, KYC documentation, claims processing",
      "CTA: bounded POC with agreed success criteria, not open-ended pilot",
      "Supporting content: EU AI Act compliance brief, model card, security documentation",
      "Competitive frame: vs. OpenAI on safety posture; vs. in-house on speed and cost",
      "Success metric: POC-to-commercial-proposal conversion rate",
    ],
  },
  {
    id: "rs-07",
    category: "role-specific",
    prompt:
      "How would you approach forecasting accuracy improvement for a team you just joined?",
    difficulty: "medium",
    idealAnswerThemes: [
      "Diagnose before prescribing: what's the current miss pattern? Optimistic or pessimistic?",
      "Audit stage definitions — vague stages produce vague forecasts",
      "Interview AEs to understand their own confidence in their commits",
      "Layer three forecasting approaches: stage-weighted, AE call, activity signals",
      "Compare forecast vs. actual by AE and by deal source — find the signal",
      "Add a sanity-check: 'what would have to go wrong for this to miss?'",
      "Establish a forecasting cadence — weekly commit, bi-weekly review",
      "Set accuracy as an explicit team metric, not just revenue attainment",
    ],
  },
  {
    id: "rs-08",
    category: "role-specific",
    prompt:
      "How would you evaluate whether an AE's territory is appropriately sized?",
    difficulty: "medium",
    idealAnswerThemes: [
      "Coverage metric: can this AE realistically work all these accounts at enterprise depth?",
      "Deal count vs. AE capacity: 15–25 active enterprise deals is typical max",
      "Pipeline creation rate: is the AE building sufficient new pipeline?",
      "Activity vs. attainment: is underperformance a territory problem or an execution problem?",
      "Benchmarking: compare territory TAM and deal count across AEs",
      "Whitespace analysis: what percentage of ICP accounts has this AE engaged?",
      "Market maturity: a new territory needs more accounts to find pipeline",
      "Recommendation: right-size if AE is working fewer than 60% of accounts at any depth",
    ],
  },
  {
    id: "rs-09",
    category: "role-specific",
    prompt:
      "What does your ideal RevOps setup look like for a 15-person enterprise sales team?",
    difficulty: "medium",
    idealAnswerThemes: [
      "Salesforce as system of record — no exceptions",
      "SEP (Outreach/Salesloft) for sequencing and activity logging",
      "Gong or similar for call recording and deal signals",
      "BI layer (Tableau or Looker) for pipeline and performance dashboards",
      "Weekly pipeline review cadence with stage-level discipline",
      "Defined metric set: ARR, pipeline coverage, win rate, sales velocity, ACV",
      "RevOps person or function dedicated to data quality, not just reporting",
      "Comp calculation automation — reps shouldn't be doing spreadsheet math",
    ],
  },
  {
    id: "rs-10",
    category: "role-specific",
    prompt:
      "How would you design an onboarding process for a new enterprise AE in a market Anthropic hasn't entered before?",
    difficulty: "medium",
    idealAnswerThemes: [
      "30-60-90 structure with explicit milestones, not just 'learn the product'",
      "Week 1: internal — product, team, systems setup",
      "Week 2–3: customer calls with experienced AE (shadow before solo)",
      "Week 4: first outbound with feedback loop",
      "Month 2: first qualified opportunity in pipeline",
      "Month 3: first discovery presentation solo",
      "Ramp quota: 25% month 1-2, 50% month 3, 75% month 4",
      "Market education built in — DACH verticals, regulatory context, competitive landscape",
      "Certification checkpoint: can they pitch and handle top 5 objections?",
    ],
  },
  {
    id: "rs-11",
    category: "role-specific",
    prompt:
      "A VP of Sales wants to expand into the manufacturing vertical in DACH. The data is mixed. How do you advise?",
    difficulty: "hard",
    idealAnswerThemes: [
      "What does 'mixed data' mean — define it before advising",
      "Market size is large; AI adoption in manufacturing is early-stage",
      "Buyer persona in manufacturing is less digitally-native than FS or tech",
      "Longer sales education cycle required — budget for it",
      "Competitive positioning: Claude vs. industrial AI vendors (different landscape)",
      "Recommend a structured experiment: 2–3 accounts, named AE time, 90-day read",
      "Success criteria before you start — what would make this a go/no-go?",
      "Don't dilute existing FS/tech focus unless manufacturing opportunity is additive",
    ],
  },
  {
    id: "rs-12",
    category: "role-specific",
    prompt:
      "How would you structure a quarterly business review (QBR) with sales leadership?",
    difficulty: "medium",
    idealAnswerThemes: [
      "QBR is forward-looking, not a postmortem — open with next quarter, not last",
      "Section 1: performance vs. target (brief — what happened and why)",
      "Section 2: pipeline health for next quarter — coverage, stage distribution",
      "Section 3: account-level risks and opportunities",
      "Section 4: strategic priorities for the quarter",
      "Section 5: resource asks and blockers",
      "Executive audience wants judgment calls and recommendations, not raw data",
      "Pre-work: distribute data pack 48h in advance so the meeting is discussion",
    ],
  },
  {
    id: "rs-13",
    category: "role-specific",
    prompt:
      "How do you think about balancing named accounts vs. geographic territories in DACH for Anthropic?",
    difficulty: "medium",
    idealAnswerThemes: [
      "Named accounts: top 20–30 strategic targets with highest ARR potential",
      "Geographic coverage for everything else — avoids gaps and conflicts",
      "Hybrid: name the key accounts in each vertical, geo-cover the long tail",
      "DACH geography is compact — geo territories by country make sense at small team size",
      "Risk of named-only: AEs over-rotate on easy accounts, ignore greenfield",
      "Salesforce configuration must reflect the model — otherwise conflict",
      "Revisit naming at annual planning; mid-year changes require compensation adjustment",
    ],
  },
  {
    id: "rs-14",
    category: "role-specific",
    prompt:
      "What sales qualification framework would you recommend for Anthropic's enterprise motion in DACH, and why?",
    difficulty: "medium",
    idealAnswerThemes: [
      "MEDDPICC — enterprise complexity requires full rigor",
      "Paper Process component is critical in DACH: procurement timelines, DPAs, BaFin compliance",
      "Competition component matters: OpenAI/Azure is in every evaluation",
      "BANT insufficient — budget rarely exists before need is built",
      "MEDDIC if team is new to qualification frameworks — introduce P and C gradually",
      "Train on it in onboarding, coach on it in deal reviews, inspect it in QBRs",
      "Customize the Champion identification: in German enterprise, internal champions are often less visible than in US deals",
    ],
  },
  {
    id: "rs-15",
    category: "role-specific",
    prompt:
      "How would you measure the effectiveness of a new sales play after 60 days?",
    difficulty: "medium",
    idealAnswerThemes: [
      "Leading indicators (first 30 days): play activation rate (% of AEs using it), outbound response rate, meeting conversion",
      "Mid indicators (days 30–60): opportunities created from play, POC conversion rate",
      "Lagging indicators: deal win rate, cycle length, ACV — too early at 60 days",
      "Qualitative: AE feedback on what's resonating and what's not",
      "Competitive signal: is this play creating differentiation in competitive deals?",
      "Compare to control group if possible — plays run vs. not run in same period",
      "Decision at day 60: iterate, kill, or scale — not 'wait and see'",
    ],
  },
  {
    id: "rs-16",
    category: "role-specific",
    prompt:
      "What does a bottom-up plan for DACH enterprise look like — walk me through the inputs, assumptions, and outputs.",
    difficulty: "hard",
    idealAnswerThemes: [
      "Input 1: ICP-qualified account count by vertical (from TAM mapping)",
      "Input 2: AE count and ramp timeline",
      "Input 3: expected pipeline creation per AE per month (based on outbound cadence)",
      "Input 4: expected ACV by vertical",
      "Input 5: expected win rate (by stage and vertical)",
      "Input 6: average sales cycle length",
      "Model: pipeline created × win rate × ACV = new ARR",
      "Layer in expansion ARR from existing accounts",
      "Output: quarterly ARR projection by AE and vertical",
      "Reconcile with top-down target and surface the gap explicitly",
      "Sensitivity table: what happens if win rate drops 5% or ACV is 20% lower?",
    ],
  },
];

export default questions;
